// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/alt-local.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { join as join3 } from "node:path";

// src/sources/AltLocalApiSource.ts
import { readFile } from "node:fs/promises";
import { readFileSync as readFileSync2 } from "node:fs";
import * as http from "node:http";

// src/sources/altPaths.ts
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
var ALT_DEFAULT_PORT = 45623;
var ALT_PORT_TRIES = 10;
function altUserDataDir(platform = process.platform, env = process.env, home = homedir()) {
  if (platform === "darwin")
    return join(home, "Library", "Application Support", "alt");
  if (platform === "win32")
    return join(env.APPDATA || join(home, "AppData", "Roaming"), "alt");
  return join(env.XDG_CONFIG_HOME || join(home, ".config"), "alt");
}
function tokenFilePath(userData) {
  return join(userData, "http-server-token");
}
function readJson(path) {
  try {
    const v = JSON.parse(readFileSync(path, "utf8"));
    return v && typeof v === "object" ? v : null;
  } catch {
    return null;
  }
}
function readHttpServerConfig(userData) {
  const json = readJson(join(userData, "storage-httpServer.json"));
  const port = typeof json?.port === "number" && json.port > 0 && json.port < 65536 ? json.port : ALT_DEFAULT_PORT;
  const enabled = typeof json?.enabled === "boolean" ? json.enabled : null;
  return { port, enabled };
}
function dbCandidates(userData) {
  const dir = join(userData, "data", "database");
  if (!existsSync(dir))
    return [];
  const out = [];
  const active = readJson(join(userData, "storage-desktopSync.json"))?.activeProfileUserId;
  if (typeof active === "string" && active) {
    const digest = createHash("sha256").update(active).digest("hex").slice(0, 16);
    out.push(join(dir, `powersync-store.account-${digest}.db`));
  }
  let names = [];
  try {
    names = readdirSync(dir);
  } catch {
    names = [];
  }
  const accounts = names.filter((n) => /^powersync-store\.account-[0-9a-f]+\.db$/.test(n)).map((n) => join(dir, n)).sort((a, b) => mtime(b) - mtime(a));
  out.push(...accounts, join(dir, "powersync-store.db"), join(dir, "lecture_notes.db"));
  return Array.from(new Set(out)).filter((p) => existsSync(p));
}
function mtime(path) {
  try {
    const wal = `${path}-wal`;
    return Math.max(statSync(path).mtimeMs, existsSync(wal) ? statSync(wal).mtimeMs : 0);
  } catch {
    return 0;
  }
}

// src/sources/plateToMarkdown.ts
function isText(n) {
  return typeof n.text === "string";
}
function escapeText(s) {
  return s.replace(/([\\`*_[\]])/g, "\\$1");
}
function renderLeaf(n) {
  const raw = n.text ?? "";
  if (raw === "")
    return "";
  if (n.code)
    return "`" + raw.replace(/`/g, "\u02CB") + "`";
  const s = escapeText(raw);
  const lead = s.match(/^\s*/)[0];
  const trail = s.match(/\s*$/)[0];
  let core = s.trim();
  if (core === "")
    return s;
  if (n.bold)
    core = `**${core}**`;
  if (n.italic)
    core = `*${core}*`;
  if (n.strikethrough)
    core = `~~${core}~~`;
  if (n.underline)
    core = `<u>${core}</u>`;
  return lead + core + trail;
}
function formatMs(ms) {
  const total = Math.max(0, Math.floor(ms / 1e3));
  const h = Math.floor(total / 3600);
  const m = Math.floor(total % 3600 / 60);
  const sec = total % 60;
  const mm = String(m).padStart(2, "0");
  const ss = String(sec).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}
function renderInline(nodes) {
  if (!nodes)
    return "";
  return nodes.map((n) => {
    if (isText(n))
      return renderLeaf(n);
    switch (n.type) {
      case "a": {
        const label = renderInline(n.children) || String(n.url ?? "");
        return n.url ? `[${label}](${String(n.url)})` : label;
      }
      case "inline_equation":
        return n.texExpression ? `$${String(n.texExpression)}$` : renderInline(n.children);
      case "mention":
        return n.value ? `@${String(n.value)}` : renderInline(n.children);
      case "recording_timestamp":
        return typeof n.ms === "number" ? `[${formatMs(n.ms)}]` : renderInline(n.children);
      default:
        return renderInline(n.children);
    }
  }).join("");
}
function tableToMarkdown(table) {
  const rows = (table.children ?? []).map(
    (tr) => (tr.children ?? []).map(
      (cell) => (cell.children ?? []).map((c) => isText(c) ? renderLeaf(c) : renderInline(c.children)).join(" ").replace(/\|/g, "\\|").replace(/\n+/g, " ").trim()
    )
  );
  if (rows.length === 0)
    return "";
  const width = Math.max(...rows.map((r) => r.length));
  const pad = (r) => [...r, ...new Array(width - r.length).fill("")];
  const line = (r) => `| ${pad(r).join(" | ")} |`;
  return [line(rows[0]), line(new Array(width).fill("---")), ...rows.slice(1).map(line)].join("\n");
}
function plateToMarkdown(doc) {
  if (!Array.isArray(doc))
    return "";
  const blocks = [];
  const counters = /* @__PURE__ */ new Map();
  let prevWasList = false;
  for (const node of doc) {
    if (!node || typeof node !== "object")
      continue;
    const type = node.type ?? "p";
    const listStyle = typeof node.listStyleType === "string" ? node.listStyleType : null;
    const indent = typeof node.indent === "number" && node.indent > 0 ? node.indent : 0;
    if (listStyle) {
      const level = Math.max(1, indent);
      for (const k of Array.from(counters.keys()))
        if (k > level)
          counters.delete(k);
      const pad = "  ".repeat(level - 1);
      const text = renderInline(node.children).trim();
      let bullet = "-";
      if (listStyle === "decimal" || listStyle === "lower-alpha" || listStyle === "upper-alpha" || listStyle === "lower-roman" || listStyle === "upper-roman") {
        const start = typeof node.listStart === "number" ? node.listStart : (counters.get(level) ?? 0) + 1;
        counters.set(level, start);
        bullet = `${start}.`;
      }
      if (type.match(/^h[1-6]$/)) {
        blocks.push(`${pad}${bullet} ${"#".repeat(Number(type[1]))} ${text}`);
      } else {
        blocks.push(`${pad}${bullet} ${text}`);
      }
      prevWasList = true;
      continue;
    }
    counters.clear();
    if (prevWasList)
      blocks.push("");
    prevWasList = false;
    const m = type.match(/^h([1-6])$/);
    if (m) {
      blocks.push(`${"#".repeat(Number(m[1]))} ${renderInline(node.children).trim()}`, "");
      continue;
    }
    switch (type) {
      case "blockquote": {
        const text = renderInline(node.children).trim();
        blocks.push(text.split("\n").map((l) => `> ${l}`).join("\n"), "");
        break;
      }
      case "code_block": {
        const lines = (node.children ?? []).map(
          (line) => (line.children ?? []).map((c) => isText(c) ? c.text : "").join("")
        );
        const lang = typeof node.lang === "string" ? node.lang : "";
        blocks.push("```" + lang, ...lines, "```", "");
        break;
      }
      case "hr":
        blocks.push("---", "");
        break;
      case "table":
        blocks.push(tableToMarkdown(node), "");
        break;
      case "equation":
        blocks.push(`$$
${String(node.texExpression ?? renderInline(node.children))}
$$`, "");
        break;
      default: {
        const text = renderInline(node.children).trim();
        blocks.push(text, "");
      }
    }
  }
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}
function componentTextToMarkdown(contentText, metadata) {
  if (!contentText)
    return "";
  let format = "";
  try {
    const meta = typeof metadata === "string" ? JSON.parse(metadata) : metadata;
    format = meta?.contentFormat ?? "";
  } catch {
    format = "";
  }
  const trimmed = contentText.trim();
  if (format === "plate-json" || trimmed.startsWith("[{")) {
    try {
      return plateToMarkdown(JSON.parse(trimmed));
    } catch {
      return trimmed;
    }
  }
  return trimmed;
}

// src/sources/altRows.ts
function folderChain(folderId, folders) {
  const names = [];
  const seen = /* @__PURE__ */ new Set();
  let id = folderId;
  while (id && !seen.has(id)) {
    seen.add(id);
    const f = folders.get(id);
    if (!f)
      break;
    names.unshift(f.name);
    id = f.parent_id;
  }
  return names;
}
function toSummary(row, folders) {
  return {
    id: row.id,
    title: (row.title ?? "").trim() || "(\uC81C\uBAA9 \uC5C6\uC74C)",
    type: row.type ?? "",
    lectureDate: row.lecture_date ? String(row.lecture_date).slice(0, 10) : null,
    folderId: row.folder_id,
    folderPath: folderChain(row.folder_id, folders),
    updatedAt: row.updated_at ?? null
  };
}
function parseTranscript(contentText) {
  if (!contentText)
    return [];
  let entries;
  try {
    const v = JSON.parse(contentText);
    if (!Array.isArray(v))
      return [];
    entries = v;
  } catch {
    return [];
  }
  const out = [];
  entries.forEach((entry, i) => {
    if (!entry || typeof entry !== "object")
      return;
    if (Array.isArray(entry.segments) && entry.segments.length > 0) {
      for (const s of entry.segments) {
        const text2 = typeof s?.text === "string" ? s.text.trim() : "";
        if (!text2)
          continue;
        const start2 = typeof s.start === "number" ? s.start : null;
        const end2 = typeof s.end === "number" ? s.end : start2;
        out.push({ startMs: start2, endMs: end2, text: text2, speaker: typeof s.speaker === "string" ? s.speaker : entry.speaker ?? "" });
      }
      return;
    }
    const text = typeof entry.originalText === "string" ? entry.originalText.trim() : "";
    if (!text)
      return;
    const start = typeof entry.relativeStart === "number" ? entry.relativeStart : null;
    const next = entries[i + 1]?.relativeStart;
    const end = start !== null && typeof next === "number" && next > start ? next : start !== null ? start + 1 : null;
    out.push({ startMs: start, endMs: end, text, speaker: entry.speaker ?? "" });
  });
  if (out.every((s) => s.startMs !== null))
    out.sort((a, b) => a.startMs - b.startMs);
  return out;
}
function transcriptMinutes(segments) {
  let end = 0;
  for (const s of segments)
    if (s.endMs !== null && s.endMs > end)
      end = s.endMs;
  return segments.length > 0 ? Math.max(1, Math.round(end / 6e4)) : null;
}
function byOrder(a, b) {
  return (a.display_order ?? 0) - (b.display_order ?? 0);
}
function pickSlides(components) {
  const slides = components.filter((c) => c.component_type === "slides").sort(byOrder);
  return slides.find((c) => !!c.file_path) ?? slides[0] ?? null;
}
function detailsFromComponents(components) {
  const slides = pickSlides(components);
  const transcript = components.filter((c) => c.component_type === "transcript").flatMap((c) => parseTranscript(c.content_text));
  return {
    hasSlides: !!slides,
    slidesTitle: slides?.title ?? null,
    pdfPath: slides?.file_path ?? null,
    transcriptMinutes: transcriptMinutes(transcript),
    timestamps: transcript.some((s) => s.startMs !== null)
  };
}
function slideIndexOf(metadata) {
  try {
    const v = metadata ? JSON.parse(metadata) : null;
    return typeof v?.slideIndex === "number" ? v.slideIndex : null;
  } catch {
    return null;
  }
}
function inferSubject(folderPath, title) {
  const code = (s) => s.match(/([A-Za-z]{2,}[\s-]?\d{2,}[A-Za-z]?)/)?.[1]?.replace(/[\s-]+/g, "").toUpperCase() ?? null;
  for (let i = folderPath.length - 1; i >= 0; i--) {
    const c = code(folderPath[i]);
    if (c)
      return c;
  }
  if (folderPath.length > 0) {
    const top = folderPath[0];
    const head = top.split(":")[0].trim();
    return head || top.trim();
  }
  return code(title) ?? "\uBBF8\uBD84\uB958";
}
async function bundleFromRows(input) {
  const { note, components } = input;
  const warnings = [];
  const slides = pickSlides(components);
  let pdf = null;
  const pdfPath = slides?.file_path ?? null;
  if (slides && !pdfPath)
    warnings.push("\uC2AC\uB77C\uC774\uB4DC PDF \uD30C\uC77C \uACBD\uB85C\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uC2AC\uB77C\uC774\uB4DC \uC5C6\uC774 \uAC00\uC838\uC635\uB2C8\uB2E4.");
  if (pdfPath) {
    try {
      pdf = await input.readFile(pdfPath);
    } catch (e) {
      warnings.push(`\uC2AC\uB77C\uC774\uB4DC PDF\uB97C \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${e instanceof Error ? e.message : String(e)}). \uC2AC\uB77C\uC774\uB4DC \uC5C6\uC774 \uAC00\uC838\uC635\uB2C8\uB2E4.`);
    }
  }
  const transcript = components.filter((c) => c.component_type === "transcript").sort(byOrder).flatMap((c) => parseTranscript(c.content_text));
  const summary = components.filter((c) => c.component_type === "summary").sort(byOrder).map((c) => componentTextToMarkdown(c.content_text, c.metadata)).filter((t) => t.trim().length > 0).join("\n\n");
  const memos = [];
  for (const c of components.filter((c2) => c2.component_type === "memo" || c2.component_type === "meeting_notes").sort(byOrder)) {
    const md = componentTextToMarkdown(c.content_text, c.metadata);
    if (md.trim())
      memos.push(md);
  }
  const slideMemos = components.filter((c) => c.component_type === "slide_memo").map((c) => ({ index: slideIndexOf(c.metadata), md: componentTextToMarkdown(c.content_text, c.metadata) })).filter((m) => m.md.trim().length > 0).sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  for (const m of slideMemos)
    memos.push(`### \uC2AC\uB77C\uC774\uB4DC ${m.index ?? "?"} \uBA54\uBAA8

${m.md}`);
  const summaryRow = toSummary(note, input.folders);
  return {
    sourceId: note.id,
    sourceKind: "alt-local",
    title: summaryRow.title,
    lectureDate: summaryRow.lectureDate ?? void 0,
    folderPath: summaryRow.folderPath,
    pdf,
    pdfPath,
    slideTexts: null,
    transcript,
    summaryMarkdown: summary || void 0,
    memoMarkdown: memos.length > 0 ? memos.join("\n\n") : void 0,
    warnings
  };
}

// src/sources/AltLocalApiSource.ts
var HOST = "127.0.0.1";
var AltApiError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    this.name = "AltApiError";
  }
};
function request2(port, path, token, timeoutMs) {
  return new Promise((resolve, reject) => {
    const headers = { Accept: "application/json" };
    if (token)
      headers.Authorization = `Bearer ${token}`;
    const req = http.request({ host: HOST, port, path, method: "GET", headers, timeout: timeoutMs }, (res) => {
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve({ status: res.statusCode ?? 0, body: Buffer.concat(chunks).toString("utf8") }));
      res.on("error", reject);
    });
    req.on("timeout", () => req.destroy(new Error("timeout")));
    req.on("error", reject);
    req.end();
  });
}
async function probeAltStatus(port, timeoutMs = 800) {
  try {
    const res = await request2(port, "/api/status", null, timeoutMs);
    if (res.status !== 200)
      return null;
    const json = JSON.parse(res.body);
    const data = json?.data;
    if (json?.ok === true && data && data.ok === true && typeof data.version === "string")
      return { version: data.version };
    return null;
  } catch {
    return null;
  }
}
function flattenFolders(tree, out) {
  if (!Array.isArray(tree))
    return;
  for (const f of tree) {
    if (!f || typeof f.id !== "string")
      continue;
    out.set(f.id, { id: f.id, name: String(f.name ?? ""), parent_id: typeof f.parent_id === "string" ? f.parent_id : null });
    flattenFolders(f.children, out);
  }
}
function componentFromApi(raw) {
  const file = raw.file;
  return {
    id: String(raw.id),
    note_id: String(raw.note_id),
    component_type: String(raw.component_type ?? ""),
    title: typeof raw.title === "string" ? raw.title : null,
    content_text: typeof raw.content_text === "string" ? raw.content_text : null,
    metadata: typeof raw.metadata === "string" ? raw.metadata : raw.metadata ? JSON.stringify(raw.metadata) : null,
    display_order: typeof raw.display_order === "number" ? raw.display_order : 0,
    file_path: typeof file?.file_path === "string" ? file.file_path : null
  };
}
var AltLocalApiSource = class _AltLocalApiSource {
  constructor(opts) {
    this.mode = "api";
    this.folders = null;
    this.port = opts.port;
    this.token = opts.token;
    this.timeoutMs = opts.timeoutMs ?? 15e3;
    this.label = `Alt \uC5F0\uACB0\uB428 \xB7 \uB85C\uCEEC API${opts.version ? ` (v${opts.version})` : ""}`;
  }
  /**
   * Finds a running Alt: /api/status on the configured port and the next
   * ones Alt falls back to. Null when Alt does not answer or the token file
   * cannot be read; `reason` says why.
   */
  static async detect(userData, probeTimeoutMs = 800) {
    const { port, enabled } = readHttpServerConfig(userData);
    for (let p = port; p < port + ALT_PORT_TRIES; p++) {
      const status = await probeAltStatus(p, probeTimeoutMs);
      if (!status)
        continue;
      let token;
      try {
        token = readFileSync2(tokenFilePath(userData), "utf8").trim();
      } catch {
        return { source: null, reason: "Alt\uB294 \uC2E4\uD589 \uC911\uC774\uC9C0\uB9CC \uB85C\uCEEC API \uD1A0\uD070 \uD30C\uC77C\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4." };
      }
      if (!token)
        return { source: null, reason: "Alt \uB85C\uCEEC API \uD1A0\uD070 \uD30C\uC77C\uC774 \uBE44\uC5B4 \uC788\uC2B5\uB2C8\uB2E4." };
      return { source: new _AltLocalApiSource({ port: p, token, version: status.version }), reason: "" };
    }
    return {
      source: null,
      reason: enabled === false ? "Alt \uC124\uC815\uC5D0\uC11C \uB85C\uCEEC HTTP \uC11C\uBC84\uAC00 \uAEBC\uC838 \uC788\uC2B5\uB2C8\uB2E4." : "Alt\uAC00 \uC2E4\uD589 \uC911\uC774 \uC544\uB2C8\uAC70\uB098 \uB85C\uCEEC API\uAC00 \uC751\uB2F5\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4."
    };
  }
  async get(path) {
    let res;
    try {
      res = await request2(this.port, path, this.token, this.timeoutMs);
    } catch (e) {
      throw new AltApiError(`Alt \uB85C\uCEEC API\uC5D0 \uC5F0\uACB0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${e instanceof Error ? e.message : String(e)}`, null);
    }
    if (res.status === 401)
      throw new AltApiError("Alt \uB85C\uCEEC API\uAC00 \uD1A0\uD070\uC744 \uAC70\uBD80\uD588\uC2B5\uB2C8\uB2E4. Alt\uB97C \uB2E4\uC2DC \uC2DC\uC791\uD55C \uB4A4 \uC0C8\uB85C\uACE0\uCE68\uD558\uC138\uC694.", 401);
    let json;
    try {
      json = JSON.parse(res.body);
    } catch {
      throw new AltApiError(`Alt \uB85C\uCEEC API \uC751\uB2F5\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (HTTP ${res.status})`, res.status);
    }
    if (res.status !== 200 || json.ok !== true) {
      throw new AltApiError(`Alt \uB85C\uCEEC API \uC624\uB958 (HTTP ${res.status}): ${typeof json.error === "string" ? json.error : "\uC54C \uC218 \uC5C6\uC74C"}`, res.status);
    }
    return json.data;
  }
  async folderMap(refresh = false) {
    if (this.folders && !refresh)
      return this.folders;
    const map = /* @__PURE__ */ new Map();
    flattenFolders(await this.get("/api/folders/tree"), map);
    this.folders = map;
    return map;
  }
  async listNotes() {
    const [rows, folders] = await Promise.all([this.get("/api/lectureNotes"), this.folderMap(true)]);
    if (!Array.isArray(rows))
      throw new AltApiError("Alt \uB85C\uCEEC API\uC758 \uB178\uD2B8 \uBAA9\uB85D \uD615\uC2DD\uC774 \uC608\uC0C1\uACFC \uB2E4\uB985\uB2C8\uB2E4.", 200);
    return rows.filter((r) => r && typeof r.id === "string").map((r) => toSummary(r, folders));
  }
  async components(id) {
    const raw = await this.get(`/api/noteComponents/note/${encodeURIComponent(id)}`);
    if (!Array.isArray(raw))
      throw new AltApiError("Alt \uB85C\uCEEC API\uC758 \uCEF4\uD3EC\uB10C\uD2B8 \uD615\uC2DD\uC774 \uC608\uC0C1\uACFC \uB2E4\uB985\uB2C8\uB2E4.", 200);
    return raw.map(componentFromApi);
  }
  async noteDetails(id) {
    return detailsFromComponents(await this.components(id));
  }
  async getBundle(id) {
    const note = await this.get(`/api/lectureNotes/${encodeURIComponent(id)}`);
    if (!note || typeof note.id !== "string")
      throw new AltApiError("Alt\uC5D0\uC11C \uC774 \uB178\uD2B8\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.", 404);
    const [folders, components] = await Promise.all([this.folderMap(), this.components(id)]);
    return bundleFromRows({
      note,
      folders,
      components,
      readFile: async (p) => {
        const buf = await readFile(p);
        return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
      }
    });
  }
};

// src/sources/AltLocalDbSource.ts
import { copyFileSync, constants, existsSync as existsSync2, mkdtempSync, rmSync } from "node:fs";
import { readFile as readFile2 } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join as join2 } from "node:path";
var KNOWN_SCHEMA_VERSIONS = [40];
var REQUIRED_COLUMNS = {
  lecture_notes: ["id", "folder_id", "title", "lecture_date", "type", "updated_at", "deleted_at"],
  folders: ["id", "name", "parent_id", "deleted_at"],
  note_components: ["id", "note_id", "component_type", "title", "content_text", "metadata", "display_order", "file_inode", "deleted_at"],
  file_metadata: ["inode", "file_path"]
};
var AltDbError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "AltDbError";
  }
};
function loadSqlite() {
  const proc = process;
  try {
    const mod = proc.getBuiltinModule?.("node:sqlite");
    if (mod)
      return mod;
  } catch {
  }
  const req = globalThis.require;
  if (typeof req === "function") {
    try {
      return req("node:sqlite");
    } catch {
    }
  }
  throw new AltDbError(
    "\uC774 Obsidian\uC5D0\uB294 \uB0B4\uC7A5 SQLite(node:sqlite)\uAC00 \uC5C6\uC5B4 Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uC77D\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. Obsidian \uC124\uCE58 \uD30C\uC77C\uC744 \uCD5C\uC2E0\uC73C\uB85C \uBC1B\uAC70\uB098, Alt\uB97C \uC2E4\uD589\uD574 \uB85C\uCEEC API\uB85C \uAC00\uC838\uC624\uC138\uC694."
  );
}
function checkSchema(db) {
  const missing = [];
  for (const [table, cols] of Object.entries(REQUIRED_COLUMNS)) {
    const have = new Set(db.prepare(`SELECT name FROM pragma_table_info('${table}')`).all().map((r) => r.name));
    if (have.size === 0) {
      missing.push(`${table} \uD14C\uC774\uBE14`);
      continue;
    }
    for (const c of cols)
      if (!have.has(c))
        missing.push(`${table}.${c}`);
  }
  let version = null;
  try {
    const row = db.prepare("SELECT MAX(version) AS v FROM migrations").get();
    version = typeof row?.v === "number" ? row.v : null;
  } catch {
    version = null;
  }
  if (missing.length > 0) {
    throw new AltDbError(
      `\uC54C \uC218 \uC5C6\uB294 Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC2A4\uD0A4\uB9C8\uC785\uB2C8\uB2E4 (\uBC84\uC804 ${version ?? "?"}, \uC5C6\uB294 \uD56D\uBAA9: ${missing.slice(0, 6).join(", ")}). Alt\uB97C \uC2E4\uD589\uD574 \uB85C\uCEEC API\uB85C \uAC00\uC838\uC624\uC138\uC694.`
    );
  }
  return { version, known: version !== null && KNOWN_SCHEMA_VERSIONS.includes(version) };
}
function hasColumn(db, table, column) {
  return db.prepare(`SELECT name FROM pragma_table_info('${table}')`).all().some((r) => r.name === column);
}
var AltLocalDbSource = class _AltLocalDbSource {
  constructor(db, copyDir, schema, storeName, hasFileRefs) {
    this.db = db;
    this.copyDir = copyDir;
    this.hasFileRefs = hasFileRefs;
    this.mode = "db";
    this.schema = schema;
    this.storeName = storeName;
    this.label = `Alt \uAEBC\uC9D0 \xB7 DB \uC77D\uAE30${schema.known ? "" : ` (\uD655\uC778\uB418\uC9C0 \uC54A\uC740 \uC2A4\uD0A4\uB9C8 v${schema.version ?? "?"})`}`;
  }
  /**
   * Copies the best store (signed-in account first) to a temp folder and
   * opens the copy. A store without notes is skipped when another has some.
   */
  static open(opts) {
    const candidates = dbCandidates(opts.userData);
    if (candidates.length === 0)
      throw new AltDbError("Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. Alt\uAC00 \uC774 \uCEF4\uD4E8\uD130\uC5D0 \uC124\uCE58\uB418\uC5B4 \uC788\uB294\uC9C0 \uD655\uC778\uD558\uC138\uC694.");
    const sqlite = opts.sqlite ?? loadSqlite();
    let fallback = null;
    let lastError = null;
    for (const file of candidates) {
      let source;
      try {
        source = _AltLocalDbSource.openCopy(file, sqlite, opts.tmpRoot ?? tmpdir());
      } catch (e) {
        if (e instanceof AltDbError) {
          fallback?.close();
          throw e;
        }
        if (file === candidates[0]) {
          throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC0AC\uBCF8\uC744 \uC5F4\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${basename(file)}): ${e instanceof Error ? e.message : String(e)}. \uC7A0\uC2DC \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC138\uC694.`);
        }
        lastError = e;
        continue;
      }
      let count;
      try {
        count = source.noteCount();
      } catch (e) {
        source.close();
        fallback?.close();
        throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC0AC\uBCF8\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${basename(file)}): ${e instanceof Error ? e.message : String(e)}. \uC7A0\uC2DC \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC138\uC694.`);
      }
      if (count > 0) {
        fallback?.close();
        return source;
      }
      if (!fallback)
        fallback = source;
      else
        source.close();
    }
    if (fallback)
      return fallback;
    throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uC5F4\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${lastError instanceof Error ? lastError.message : String(lastError)}`);
  }
  static openCopy(file, sqlite, tmpRoot) {
    const dir = mkdtempSync(join2(tmpRoot, "alt2obs-altdb-"));
    try {
      const target = join2(dir, basename(file));
      copyFileSync(file, target, constants.COPYFILE_FICLONE);
      if (existsSync2(`${file}-wal`))
        copyFileSync(`${file}-wal`, `${target}-wal`, constants.COPYFILE_FICLONE);
      const db = new sqlite.DatabaseSync(target);
      try {
        db.exec("PRAGMA query_only = 1");
        const schema = checkSchema(db);
        return new _AltLocalDbSource(db, dir, schema, basename(file), hasColumn(db, "note_components", "file_ref_id"));
      } catch (e) {
        db.close();
        throw e;
      }
    } catch (e) {
      rmSync(dir, { recursive: true, force: true });
      throw e;
    }
  }
  noteCount() {
    const row = this.db.prepare("SELECT COUNT(*) AS c FROM lecture_notes WHERE deleted_at IS NULL").get();
    return row.c;
  }
  folderMap() {
    const rows = this.db.prepare("SELECT id, name, parent_id FROM folders WHERE deleted_at IS NULL").all();
    return new Map(rows.map((r) => [r.id, { id: r.id, name: r.name, parent_id: r.parent_id }]));
  }
  async listNotes() {
    const folders = this.folderMap();
    const rows = this.db.prepare("SELECT id, title, type, lecture_date, folder_id, updated_at FROM lecture_notes WHERE deleted_at IS NULL ORDER BY lecture_date DESC, id DESC").all();
    return rows.map((r) => toSummary(r, folders));
  }
  components(noteId) {
    const refJoin = this.hasFileRefs ? "LEFT JOIN file_ref_local_files fl ON fl.file_ref_id = nc.file_ref_id" : "";
    const refPath = this.hasFileRefs ? "NULLIF(fl.local_cache_path, '')" : "NULL";
    const sql = `SELECT nc.id, nc.note_id, nc.component_type, nc.title, nc.content_text, nc.metadata, nc.display_order,
                        COALESCE(NULLIF(fm.file_path, ''), ${refPath}) AS file_path
                   FROM note_components nc
                   LEFT JOIN file_metadata fm ON fm.inode = nc.file_inode
                   ${refJoin}
                  WHERE nc.note_id = ? AND nc.deleted_at IS NULL
                  ORDER BY nc.display_order, nc.component_type, nc.title, nc.id`;
    try {
      return this.db.prepare(sql).all(noteId);
    } catch (e) {
      if (!this.hasFileRefs)
        throw e;
      this.hasFileRefs = false;
      return this.components(noteId);
    }
  }
  async noteDetails(id) {
    return detailsFromComponents(this.components(id));
  }
  async getBundle(id) {
    const note = this.db.prepare("SELECT id, title, type, lecture_date, folder_id, updated_at FROM lecture_notes WHERE id = ? AND deleted_at IS NULL").get(id);
    if (!note)
      throw new AltDbError("Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uC5D0\uC11C \uC774 \uB178\uD2B8\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.");
    return bundleFromRows({
      note,
      folders: this.folderMap(),
      components: this.components(id),
      readFile: async (p) => {
        const buf = await readFile2(p);
        return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
      }
    });
  }
  close() {
    try {
      this.db.close();
    } catch {
    }
    rmSync(this.copyDir, { recursive: true, force: true });
  }
};

// src/sources/index.ts
async function connectAltLocal(userData, opts = {}) {
  const api = await AltLocalApiSource.detect(userData, opts.probeTimeoutMs);
  if (api.source)
    return { source: api.source, label: api.source.label, detail: "" };
  try {
    const db = AltLocalDbSource.open({ userData, sqlite: opts.sqlite, tmpRoot: opts.tmpRoot });
    return { source: db, label: db.label, detail: api.reason };
  } catch (e) {
    return { source: null, label: "\uC5F0\uACB0 \uC548 \uB428", detail: `${api.reason} ${e instanceof Error ? e.message : String(e)}`.trim() };
  }
}

// scripts/src/cli-common.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/alt-local.ts
function option(args, name) {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : void 0;
}
async function connect(userData, mode) {
  if (mode === "api") {
    const r = await AltLocalApiSource.detect(userData);
    return { source: r.source, label: r.source?.label ?? "\uC5F0\uACB0 \uC548 \uB428", detail: r.reason };
  }
  if (mode === "db") {
    const db = AltLocalDbSource.open({ userData });
    return { source: db, label: db.label, detail: "" };
  }
  return connectAltLocal(userData);
}
async function main() {
  const args = process.argv.slice(2);
  const pos = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("--"))
      i++;
    else
      pos.push(args[i]);
  }
  const cmd = pos[0];
  const userData = option(args, "--alt-dir") ?? altUserDataDir();
  const mode = option(args, "--source") ?? "auto";
  if (!["status", "list", "export"].includes(cmd) || !["auto", "api", "db"].includes(mode)) {
    process.stderr.write("Usage: node scripts/phase2/alt-local.mjs status | list [--query T] | export <noteId> <outDir> [--alt-dir DIR] [--source auto|api|db]\n");
    process.exit(2);
  }
  const conn = await connect(userData, mode);
  const source = conn.source;
  try {
    if (cmd === "status") {
      process.stdout.write(JSON.stringify({ mode: source?.mode ?? "none", label: conn.label, detail: conn.detail }) + "\n");
      return;
    }
    if (!source)
      throw new Error(`Alt\uC5D0 \uC5F0\uACB0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${conn.detail}`);
    if (cmd === "list") {
      const q = (option(args, "--query") ?? "").toLowerCase();
      const notes = (await source.listNotes()).filter((n) => !q || n.title.toLowerCase().includes(q) || n.folderPath.join("/").toLowerCase().includes(q)).map((n) => ({ id: n.id, title: n.title, type: n.type, lectureDate: n.lectureDate, folderPath: n.folderPath, subject: inferSubject(n.folderPath, n.title) }));
      process.stdout.write(JSON.stringify({ mode: source.mode, notes }) + "\n");
      return;
    }
    const [, id, outDir] = pos;
    if (!id || !outDir)
      throw new Error("export needs <noteId> <outDir>");
    const bundle = await source.getBundle(id);
    mkdirSync(outDir, { recursive: true });
    const { pdf: _pdf, ...rest } = bundle;
    const out = { ...rest, subject: inferSubject(bundle.folderPath ?? [], bundle.title) };
    const bundlePath = join3(outDir, "bundle.json");
    writeFileSync(bundlePath, JSON.stringify(out, null, 1));
    writeFileSync(join3(outDir, "transcript.txt"), bundle.transcript.map((s) => s.text).join("\n"));
    process.stdout.write(
      JSON.stringify({
        bundle: bundlePath,
        pdfPath: bundle.pdf ? bundle.pdfPath : null,
        segments: bundle.transcript.length,
        timestamps: bundle.transcript.some((s) => s.startMs !== null),
        warnings: bundle.warnings ?? []
      }) + "\n"
    );
  } finally {
    source?.close?.();
  }
}
main().catch((e) => fail(e, "alt-local"));
