// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/alt-local.ts
import { mkdirSync, mkdtempSync as mkdtempSync2, writeFileSync } from "node:fs";
import { tmpdir as tmpdir2 } from "node:os";
import { join as join4 } from "node:path";

// src/sources/AltLocalApiSource.ts
import { readFile } from "node:fs/promises";
import { readFileSync as readFileSync3 } from "node:fs";
import * as http from "node:http";

// src/sources/altPaths.ts
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
var ALT_DEFAULT_PORT = 45623;
var ALT_PORT_TRIES = 10;
function altUserDataDir(platform = process.platform, env = process.env, home = homedir()) {
  if (platform === "darwin")
    return join(home, "Library", "Application Support", "alt");
  if (platform === "win32")
    return join(env.APPDATA || join(home, "AppData", "Roaming"), "alt");
  return join(env.XDG_CONFIG_HOME || join(home, ".config"), "alt");
}
function tokenFilePath(userData) {
  return join(userData, "http-server-token");
}
function readJson(path) {
  try {
    const v = JSON.parse(readFileSync(path, "utf8"));
    return v && typeof v === "object" ? v : null;
  } catch {
    return null;
  }
}
function readHttpServerConfig(userData) {
  const json = readJson(join(userData, "storage-httpServer.json"));
  const port = typeof json?.port === "number" && json.port > 0 && json.port < 65536 ? json.port : ALT_DEFAULT_PORT;
  const enabled = typeof json?.enabled === "boolean" ? json.enabled : null;
  return { port, enabled };
}
function activeProfileUserId(userData) {
  const active = readJson(join(userData, "storage-desktopSync.json"))?.activeProfileUserId;
  return typeof active === "string" && active ? active : null;
}
function dbCandidates(userData) {
  const dir = join(userData, "data", "database");
  if (!existsSync(dir))
    return [];
  const out = [];
  const active = activeProfileUserId(userData);
  if (active) {
    const digest = createHash("sha256").update(active).digest("hex").slice(0, 16);
    out.push({ path: join(dir, `powersync-store.account-${digest}.db`), accountId: active });
  } else {
    let names = [];
    try {
      names = readdirSync(dir);
    } catch {
      names = [];
    }
    names.filter((n) => /^powersync-store\.account-[0-9a-f]+\.db$/.test(n)).map((n) => join(dir, n)).sort((x, y) => mtime(y) - mtime(x)).forEach((path) => out.push({ path, accountId: void 0 }));
  }
  out.push({ path: join(dir, "powersync-store.db"), accountId: null }, { path: join(dir, "lecture_notes.db"), accountId: void 0 });
  return out.filter((c) => existsSync(c.path));
}
function mtime(path) {
  try {
    const wal = `${path}-wal`;
    return Math.max(statSync(path).mtimeMs, existsSync(wal) ? statSync(wal).mtimeMs : 0);
  } catch {
    return 0;
  }
}

// src/sources/altOwnership.ts
import { execFile } from "node:child_process";
import { readdirSync as readdirSync2, readFileSync as readFileSync2, readlinkSync } from "node:fs";
import { userInfo } from "node:os";
import { join as join2 } from "node:path";
function run(bin, args, timeoutMs = 3e3) {
  return new Promise((resolve, reject) => {
    execFile(bin, args, { timeout: timeoutMs, windowsHide: true, encoding: "utf8", maxBuffer: 4 * 1024 * 1024 }, (err, stdout) => {
      if (err && !stdout)
        reject(err);
      else
        resolve(stdout);
    });
  });
}
function parseLsof(out) {
  const res = [];
  let cur = null;
  for (const line of out.split("\n")) {
    const tag = line[0];
    const val = line.slice(1).trim();
    if (tag === "p") {
      cur = { pid: Number(val), uid: null, command: "" };
      res.push(cur);
    } else if (cur && tag === "u")
      cur.uid = Number(val);
    else if (cur && tag === "c")
      cur.command = val;
  }
  return res.filter((r) => Number.isInteger(r.pid) && r.pid > 0);
}
function parseProcNetTcp(table, port) {
  const hexPort = port.toString(16).toUpperCase().padStart(4, "0");
  const inodes = [];
  for (const line of table.split("\n").slice(1)) {
    const f = line.trim().split(/\s+/);
    if (f.length < 10)
      continue;
    const [, local, , state] = f;
    if (state === "0A" && local.toUpperCase().endsWith(`:${hexPort}`))
      inodes.push(f[9]);
  }
  return inodes;
}
function parseNetstat(out, port) {
  for (const line of out.split(/\r?\n/)) {
    const f = line.trim().split(/\s+/);
    if (f.length < 5 || f[0].toUpperCase() !== "TCP")
      continue;
    const local = f[1];
    if (!/^(127\.0\.0\.1|0\.0\.0\.0):\d+$/.test(local) || Number(local.split(":")[1]) !== port)
      continue;
    if (f[3].toUpperCase() !== "LISTENING")
      continue;
    const pid = Number(f[4]);
    if (Number.isInteger(pid) && pid > 0)
      return pid;
  }
  return null;
}
function parseTasklist(out) {
  const line = out.trim().split(/\r?\n/)[0] ?? "";
  const fields = [...line.matchAll(/"((?:[^"]|"")*)"/g)].map((m) => m[1].replace(/""/g, '"'));
  if (fields.length < 7)
    return null;
  return { image: fields[0], user: fields[6] };
}
function isSameWindowsUser(user, me) {
  if (!user || /^n\/a$/i.test(user.trim()))
    return false;
  const name = user.split("\\").pop() ?? "";
  return name.toLowerCase() === me.toLowerCase();
}
function isAltExecutable(exe, platform) {
  if (platform === "darwin")
    return /\/Alt\.app\/Contents\//.test(exe);
  if (platform === "win32")
    return /^alt\.exe$/i.test(exe.split(/[\\/]/).pop() ?? "");
  const base = exe.split("/").pop() ?? "";
  return /^alt$/i.test(base) || /\/alt\//i.test(exe);
}
async function ownerDarwin(port) {
  const out = await run("/usr/sbin/lsof", ["-nP", "-a", `-iTCP:${port}`, "-sTCP:LISTEN", "-Fpcu"]);
  const procs = parseLsof(out);
  if (procs.length !== 1)
    return null;
  const exe = (await run("/bin/ps", ["-p", String(procs[0].pid), "-o", "comm="])).trim();
  return { pid: procs[0].pid, uid: procs[0].uid, exe };
}
function ownerLinux(port) {
  const inodes = /* @__PURE__ */ new Set();
  for (const f of ["/proc/net/tcp", "/proc/net/tcp6"]) {
    try {
      for (const i of parseProcNetTcp(readFileSync2(f, "utf8"), port))
        inodes.add(i);
    } catch {
    }
  }
  if (inodes.size === 0)
    return null;
  for (const pid of readdirSync2("/proc").filter((d) => /^\d+$/.test(d))) {
    let fds;
    try {
      fds = readdirSync2(`/proc/${pid}/fd`);
    } catch {
      continue;
    }
    for (const fd of fds) {
      let target = "";
      try {
        target = readlinkSync(`/proc/${pid}/fd/${fd}`);
      } catch {
        continue;
      }
      const m = target.match(/^socket:\[(\d+)\]$/);
      if (!m || !inodes.has(m[1]))
        continue;
      const uidLine = readFileSync2(`/proc/${pid}/status`, "utf8").match(/^Uid:\s+(\d+)/m);
      return { pid: Number(pid), uid: uidLine ? Number(uidLine[1]) : null, exe: readlinkSync(`/proc/${pid}/exe`) };
    }
  }
  return null;
}
function system32(exe) {
  return join2(process.env.SystemRoot || "C:\\Windows", "System32", exe);
}
async function ownerWindows(port) {
  const pid = parseNetstat(await run(system32("netstat.exe"), ["-ano", "-p", "TCP"]), port);
  if (pid === null)
    return null;
  const task = parseTasklist(await run(system32("tasklist.exe"), ["/V", "/FI", `PID eq ${pid}`, "/FO", "CSV", "/NH"]));
  return task ? { pid, uid: null, exe: task.image, user: task.user } : null;
}
async function portOwner(port, platform = process.platform) {
  if (platform === "darwin")
    return ownerDarwin(port);
  if (platform === "win32")
    return ownerWindows(port);
  return ownerLinux(port);
}
function systemOwnerVerifier(platform = process.platform) {
  return async (port) => {
    let owner;
    try {
      owner = await portOwner(port, platform);
    } catch (e) {
      return { ok: false, reason: `\uD3EC\uD2B8 ${port}\uC758 \uD504\uB85C\uADF8\uB7A8\uC744 \uD655\uC778\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${e instanceof Error ? e.message : String(e)})` };
    }
    if (!owner)
      return { ok: false, reason: `\uD3EC\uD2B8 ${port}\uB97C \uC5F0 \uD504\uB85C\uADF8\uB7A8\uC744 \uD655\uC778\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4` };
    if (platform === "win32") {
      if (!isSameWindowsUser(owner.user ?? "", userInfo().username))
        return { ok: false, reason: `\uD3EC\uD2B8 ${port}\uC758 \uD504\uB85C\uADF8\uB7A8\uC774 \uC774 \uC0AC\uC6A9\uC790\uB85C \uC2E4\uD589\uB410\uB294\uC9C0 \uD655\uC778\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4` };
    } else {
      const myUid = typeof process.getuid === "function" ? process.getuid() : null;
      if (owner.uid === null || myUid === null || owner.uid !== myUid)
        return { ok: false, reason: `\uD3EC\uD2B8 ${port}\uC758 \uD504\uB85C\uADF8\uB7A8\uC774 \uC774 \uC0AC\uC6A9\uC790\uB85C \uC2E4\uD589\uB410\uB294\uC9C0 \uD655\uC778\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4` };
    }
    if (!isAltExecutable(owner.exe, platform))
      return { ok: false, reason: `\uD3EC\uD2B8 ${port}\uC758 \uD504\uB85C\uADF8\uB7A8\uC774 Alt\uAC00 \uC544\uB2D9\uB2C8\uB2E4 (${owner.exe.split(/[\\/]/).pop()})`, pid: owner.pid };
    return { ok: true, reason: "", pid: owner.pid };
  };
}

// src/sources/plateToMarkdown.ts
function isText(n) {
  return typeof n.text === "string";
}
function escapeText(s) {
  return s.replace(/([\\`*_[\]])/g, "\\$1");
}
function renderLeaf(n) {
  const raw = n.text ?? "";
  if (raw === "")
    return "";
  if (n.code)
    return "`" + raw.replace(/`/g, "\u02CB") + "`";
  const s = escapeText(raw);
  const lead = s.match(/^\s*/)[0];
  const trail = s.match(/\s*$/)[0];
  let core = s.trim();
  if (core === "")
    return s;
  if (n.bold)
    core = `**${core}**`;
  if (n.italic)
    core = `*${core}*`;
  if (n.strikethrough)
    core = `~~${core}~~`;
  if (n.underline)
    core = `<u>${core}</u>`;
  return lead + core + trail;
}
function formatMs(ms) {
  const total = Math.max(0, Math.floor(ms / 1e3));
  const h = Math.floor(total / 3600);
  const m = Math.floor(total % 3600 / 60);
  const sec = total % 60;
  const mm = String(m).padStart(2, "0");
  const ss = String(sec).padStart(2, "0");
  return h > 0 ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
}
function renderInline(nodes) {
  if (!nodes)
    return "";
  return nodes.map((n) => {
    if (isText(n))
      return renderLeaf(n);
    switch (n.type) {
      case "a": {
        const label = renderInline(n.children) || String(n.url ?? "");
        return n.url ? `[${label}](${String(n.url)})` : label;
      }
      case "inline_equation":
        return n.texExpression ? `$${String(n.texExpression)}$` : renderInline(n.children);
      case "mention":
        return n.value ? `@${String(n.value)}` : renderInline(n.children);
      case "recording_timestamp":
        return typeof n.ms === "number" ? `[${formatMs(n.ms)}]` : renderInline(n.children);
      default:
        return renderInline(n.children);
    }
  }).join("");
}
function tableToMarkdown(table) {
  const rows = (table.children ?? []).map(
    (tr) => (tr.children ?? []).map(
      (cell) => (cell.children ?? []).map((c) => isText(c) ? renderLeaf(c) : renderInline(c.children)).join(" ").replace(/\|/g, "\\|").replace(/\n+/g, " ").trim()
    )
  );
  if (rows.length === 0)
    return "";
  const width = Math.max(...rows.map((r) => r.length));
  const pad = (r) => [...r, ...new Array(width - r.length).fill("")];
  const line = (r) => `| ${pad(r).join(" | ")} |`;
  return [line(rows[0]), line(new Array(width).fill("---")), ...rows.slice(1).map(line)].join("\n");
}
function plateToMarkdown(doc) {
  if (!Array.isArray(doc))
    return "";
  const blocks = [];
  const counters = /* @__PURE__ */ new Map();
  let prevWasList = false;
  for (const node of doc) {
    if (!node || typeof node !== "object")
      continue;
    const type = node.type ?? "p";
    const listStyle = typeof node.listStyleType === "string" ? node.listStyleType : null;
    const indent = typeof node.indent === "number" && node.indent > 0 ? node.indent : 0;
    if (listStyle) {
      const level = Math.max(1, indent);
      for (const k of Array.from(counters.keys()))
        if (k > level)
          counters.delete(k);
      const pad = "  ".repeat(level - 1);
      const text = renderInline(node.children).trim();
      let bullet = "-";
      if (listStyle === "todo")
        bullet = node.checked ? "- [x]" : "- [ ]";
      else if (listStyle === "decimal" || listStyle === "lower-alpha" || listStyle === "upper-alpha" || listStyle === "lower-roman" || listStyle === "upper-roman") {
        const start = typeof node.listStart === "number" ? node.listStart : (counters.get(level) ?? 0) + 1;
        counters.set(level, start);
        bullet = `${start}.`;
      }
      if (type.match(/^h[1-6]$/)) {
        blocks.push(`${pad}${bullet} ${"#".repeat(Number(type[1]))} ${text}`);
      } else {
        blocks.push(`${pad}${bullet} ${text}`);
      }
      prevWasList = true;
      continue;
    }
    const todoItem = type === "action_item" || type === "todo" || type === "todo_li";
    if (!todoItem)
      counters.clear();
    if (prevWasList && !todoItem)
      blocks.push("");
    prevWasList = false;
    const m = type.match(/^h([1-6])$/);
    if (m) {
      blocks.push(`${"#".repeat(Number(m[1]))} ${renderInline(node.children).trim()}`, "");
      continue;
    }
    switch (type) {
      case "action_item":
      case "todo":
      case "todo_li": {
        const pad = "  ".repeat(Math.max(0, indent - 1));
        blocks.push(`${pad}${node.checked ? "- [x]" : "- [ ]"} ${renderInline(node.children).trim()}`);
        prevWasList = true;
        break;
      }
      case "blockquote": {
        const text = renderInline(node.children).trim();
        blocks.push(text.split("\n").map((l) => `> ${l}`).join("\n"), "");
        break;
      }
      case "code_block": {
        const lines = (node.children ?? []).map(
          (line) => (line.children ?? []).map((c) => isText(c) ? c.text : "").join("")
        );
        const lang = typeof node.lang === "string" ? node.lang : "";
        blocks.push("```" + lang, ...lines, "```", "");
        break;
      }
      case "hr":
        blocks.push("---", "");
        break;
      case "table":
        blocks.push(tableToMarkdown(node), "");
        break;
      case "equation":
        blocks.push(`$$
${String(node.texExpression ?? renderInline(node.children))}
$$`, "");
        break;
      default: {
        if (hasBlockChildren(node)) {
          const inner = plateToMarkdown(node.children);
          if (inner)
            blocks.push(type === "callout" ? inner.split("\n").map((l) => `> ${l}`.trimEnd()).join("\n") : inner, "");
          break;
        }
        const text = renderInline(node.children).trim();
        blocks.push(text, "");
      }
    }
  }
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}
var INLINE_TYPES = /* @__PURE__ */ new Set(["a", "inline_equation", "mention", "recording_timestamp"]);
function hasBlockChildren(node) {
  return (node.children ?? []).some((c) => !isText(c) && !!c.type && !INLINE_TYPES.has(c.type));
}
function plainText(value) {
  const out = [];
  const walk = (v) => {
    if (Array.isArray(v))
      v.forEach(walk);
    else if (v && typeof v === "object") {
      for (const [k, x] of Object.entries(v)) {
        if (k === "text" && typeof x === "string") {
          if (x.trim())
            out.push(x);
        } else
          walk(x);
      }
    }
  };
  walk(value);
  return out.join("\n");
}
function componentTextToMarkdown(contentText, metadata) {
  if (!contentText)
    return "";
  let format = "";
  try {
    const meta = typeof metadata === "string" ? JSON.parse(metadata) : metadata;
    format = meta?.contentFormat ?? "";
  } catch {
    format = "";
  }
  const trimmed = contentText.trim();
  if (format === "plate-json" || trimmed.startsWith("[{")) {
    try {
      const doc = JSON.parse(trimmed);
      const md = plateToMarkdown(doc);
      return md || plainText(doc).trim();
    } catch {
      return trimmed;
    }
  }
  return trimmed;
}

// src/sources/altRows.ts
function folderChain(folderId, folders) {
  const names = [];
  const seen = /* @__PURE__ */ new Set();
  let id = folderId;
  while (id && !seen.has(id)) {
    seen.add(id);
    const f = folders.get(id);
    if (!f)
      break;
    names.unshift(f.name);
    id = f.parent_id;
  }
  return names;
}
function toSummary(row, folders) {
  return {
    id: row.id,
    title: (row.title ?? "").trim() || "(\uC81C\uBAA9 \uC5C6\uC74C)",
    type: row.type ?? "",
    lectureDate: row.lecture_date ? String(row.lecture_date).slice(0, 10) : null,
    folderId: row.folder_id,
    folderPath: folderChain(row.folder_id, folders),
    updatedAt: row.updated_at ?? null
  };
}
function parseTranscript(contentText) {
  if (!contentText)
    return [];
  let entries;
  try {
    const v = JSON.parse(contentText);
    if (!Array.isArray(v))
      return [];
    entries = v;
  } catch {
    return [];
  }
  const out = [];
  entries.forEach((entry, i) => {
    if (!entry || typeof entry !== "object")
      return;
    if (Array.isArray(entry.segments) && entry.segments.length > 0) {
      for (const s of entry.segments) {
        const text2 = typeof s?.text === "string" ? s.text.trim() : "";
        if (!text2)
          continue;
        const start2 = typeof s.start === "number" ? s.start : null;
        const end2 = typeof s.end === "number" ? s.end : start2;
        out.push({ startMs: start2, endMs: end2, text: text2, speaker: typeof s.speaker === "string" ? s.speaker : entry.speaker ?? "" });
      }
      return;
    }
    const text = typeof entry.originalText === "string" ? entry.originalText.trim() : "";
    if (!text)
      return;
    const start = typeof entry.relativeStart === "number" ? entry.relativeStart : null;
    const next = entries[i + 1]?.relativeStart;
    const end = start !== null && typeof next === "number" && next > start ? next : start !== null ? start + 1 : null;
    out.push({ startMs: start, endMs: end, text, speaker: entry.speaker ?? "" });
  });
  if (out.every((s) => s.startMs !== null))
    out.sort((a, b) => a.startMs - b.startMs);
  return out;
}
function transcriptMinutes(segments) {
  let end = 0;
  for (const s of segments)
    if (s.endMs !== null && s.endMs > end)
      end = s.endMs;
  return segments.length > 0 ? Math.max(1, Math.round(end / 6e4)) : null;
}
function compareOptionalString(a, b) {
  const x = a ?? "";
  const y = b ?? "";
  return x === y ? 0 : x < y ? -1 : 1;
}
function compareForDisplay(a, b) {
  const oa = a.display_order ?? Number.MAX_SAFE_INTEGER;
  const ob = b.display_order ?? Number.MAX_SAFE_INTEGER;
  return oa - ob || compareOptionalString(a.component_type, b.component_type) || compareOptionalString(a.title, b.title) || compareOptionalString(a.id, b.id);
}
function displayComponent(components, type) {
  return [...components].sort(compareForDisplay).find((c) => c.component_type === type) ?? null;
}
function pickSlides(components) {
  return displayComponent(components, "slides");
}
function detailsFromComponents(components) {
  const slides = pickSlides(components);
  const transcript = parseTranscript(displayComponent(components, "transcript")?.content_text);
  return {
    hasSlides: !!slides,
    slidesTitle: slides?.title ?? null,
    pdfPath: slides?.file_path ?? null,
    transcriptMinutes: transcriptMinutes(transcript),
    timestamps: transcript.some((s) => s.startMs !== null)
  };
}
function slideIndexOf(metadata) {
  try {
    const v = metadata ? JSON.parse(metadata) : null;
    return typeof v?.slideIndex === "number" ? v.slideIndex : null;
  } catch {
    return null;
  }
}
function inferSubject(folderPath, title) {
  const code = (s) => s.match(/([A-Za-z]{2,}[\s-]?\d{2,}[A-Za-z]?)/)?.[1]?.replace(/[\s-]+/g, "").toUpperCase() ?? null;
  for (let i = folderPath.length - 1; i >= 0; i--) {
    const c = code(folderPath[i]);
    if (c)
      return c;
  }
  if (folderPath.length > 0) {
    const top = folderPath[0];
    const head = top.split(":")[0].trim();
    return head || top.trim();
  }
  return code(title) ?? "\uBBF8\uBD84\uB958";
}
async function bundleFromRows(input) {
  const { note, components } = input;
  const warnings = [];
  const slides = pickSlides(components);
  let pdf = null;
  const pdfPath = slides?.file_path ?? null;
  if (slides && !pdfPath) {
    warnings.push(
      slides.file_ref_id ? "\uC2AC\uB77C\uC774\uB4DC PDF\uAC00 \uB3D9\uAE30\uD654\uB41C \uD30C\uC77C\uC778\uB370 \uC774 \uCEF4\uD4E8\uD130\uC758 \uACBD\uB85C\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (Alt\uC5D0\uC11C \uC2AC\uB77C\uC774\uB4DC\uB97C \uD55C \uBC88 \uC5F4\uC5B4 \uB0B4\uB824\uBC1B\uC740 \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC138\uC694). \uC2AC\uB77C\uC774\uB4DC \uC5C6\uC774 \uAC00\uC838\uC635\uB2C8\uB2E4." : "\uC2AC\uB77C\uC774\uB4DC PDF \uD30C\uC77C \uACBD\uB85C\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uC2AC\uB77C\uC774\uB4DC \uC5C6\uC774 \uAC00\uC838\uC635\uB2C8\uB2E4."
    );
  }
  if (pdfPath) {
    try {
      pdf = await input.readFile(pdfPath);
    } catch (e) {
      warnings.push(`\uC2AC\uB77C\uC774\uB4DC PDF\uB97C \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${e instanceof Error ? e.message : String(e)}). \uC2AC\uB77C\uC774\uB4DC \uC5C6\uC774 \uAC00\uC838\uC635\uB2C8\uB2E4.`);
    }
  }
  const transcriptRow = displayComponent(components, "transcript");
  const transcript = parseTranscript(transcriptRow?.content_text);
  const summaryRow = displayComponent(components, "summary");
  const summary = summaryRow ? componentTextToMarkdown(summaryRow.content_text, summaryRow.metadata).trim() : "";
  const memos = [];
  for (const type of ["memo", "meeting_notes"]) {
    const c = displayComponent(components, type);
    const md = c ? componentTextToMarkdown(c.content_text, c.metadata) : "";
    if (md.trim())
      memos.push(md);
  }
  const slideMemos = components.filter((c) => c.component_type === "slide_memo").map((c) => ({ index: slideIndexOf(c.metadata), md: componentTextToMarkdown(c.content_text, c.metadata) })).filter((m) => m.md.trim().length > 0).sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  for (const m of slideMemos)
    memos.push(`### \uC2AC\uB77C\uC774\uB4DC ${m.index ?? "?"} \uBA54\uBAA8

${m.md}`);
  const noteInfo = toSummary(note, input.folders);
  return {
    sourceId: note.id,
    sourceKind: "alt-local",
    title: noteInfo.title,
    lectureDate: noteInfo.lectureDate ?? void 0,
    folderPath: noteInfo.folderPath,
    pdf,
    pdfPath,
    slideTexts: null,
    transcript,
    summaryMarkdown: summary || void 0,
    memoMarkdown: memos.length > 0 ? memos.join("\n\n") : void 0,
    warnings
  };
}

// src/sources/AltLocalApiSource.ts
var HOST = "127.0.0.1";
var AltApiError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    this.name = "AltApiError";
  }
};
function request2(port, path, token, timeoutMs) {
  return new Promise((resolve, reject) => {
    const headers = { Accept: "application/json" };
    if (token)
      headers.Authorization = `Bearer ${token}`;
    const req = http.request({ host: HOST, port, path, method: "GET", headers, timeout: timeoutMs }, (res) => {
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve({ status: res.statusCode ?? 0, body: Buffer.concat(chunks).toString("utf8") }));
      res.on("error", reject);
    });
    req.on("timeout", () => req.destroy(new Error("timeout")));
    req.on("error", reject);
    req.end();
  });
}
async function probeAltStatus(port, timeoutMs = 800) {
  try {
    const res = await request2(port, "/api/status", null, timeoutMs);
    if (res.status !== 200)
      return null;
    const json = JSON.parse(res.body);
    const data = json?.data;
    if (json?.ok === true && data && data.ok === true && typeof data.version === "string")
      return { version: data.version };
    return null;
  } catch {
    return null;
  }
}
function flattenFolders(tree, out) {
  if (!Array.isArray(tree))
    return;
  for (const f of tree) {
    if (!f || typeof f.id !== "string")
      continue;
    out.set(f.id, { id: f.id, name: String(f.name ?? ""), parent_id: typeof f.parent_id === "string" ? f.parent_id : null });
    flattenFolders(f.children, out);
  }
}
function componentFromApi(raw) {
  const file = raw.file;
  return {
    id: String(raw.id),
    note_id: String(raw.note_id),
    component_type: String(raw.component_type ?? ""),
    title: typeof raw.title === "string" ? raw.title : null,
    content_text: typeof raw.content_text === "string" ? raw.content_text : null,
    metadata: typeof raw.metadata === "string" ? raw.metadata : raw.metadata ? JSON.stringify(raw.metadata) : null,
    display_order: typeof raw.display_order === "number" ? raw.display_order : null,
    file_path: typeof file?.file_path === "string" ? file.file_path : null,
    file_ref_id: typeof raw.file_ref_id === "string" ? raw.file_ref_id : null
  };
}
var OWNER_RECHECK_MS = 3e3;
var AltLocalApiSource = class _AltLocalApiSource {
  constructor(opts) {
    this.mode = "api";
    this.folders = null;
    this.pathDb = null;
    this.pathMemo = /* @__PURE__ */ new Map();
    /** Set on a connection or ownership failure: the caller should connect again. */
    this.failed = false;
    this.openPathDb = opts.openPathDb;
    this.verifyOwner = opts.verifyOwner;
    this.ownerPid = opts.ownerPid ?? null;
    this.now = opts.now ?? Date.now;
    this.lastOwnerCheck = this.now();
    this.port = opts.port;
    this.token = opts.token;
    this.timeoutMs = opts.timeoutMs ?? 15e3;
    this.label = `Alt \uC5F0\uACB0\uB428 \xB7 \uB85C\uCEEC API${opts.version ? ` (v${opts.version})` : ""}`;
  }
  /**
   * Finds a running Alt: /api/status on the configured port and the next
   * ones Alt falls back to. Null when Alt does not answer or the token file
   * cannot be read; `reason` says why.
   */
  static async detect(userData, opts = {}) {
    const { port, enabled } = readHttpServerConfig(userData);
    const verify = opts.verifyOwner ?? systemOwnerVerifier();
    let refused = "";
    for (let p = port; p < port + ALT_PORT_TRIES; p++) {
      const status = await probeAltStatus(p, opts.probeTimeoutMs ?? 800);
      if (!status)
        continue;
      const owner = await verify(p);
      if (!owner.ok || owner.pid === void 0) {
        refused = refused || owner.reason || "\uD3EC\uD2B8\uC758 \uD504\uB85C\uC138\uC2A4\uB97C \uD655\uC778\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4";
        continue;
      }
      let token;
      try {
        token = readFileSync3(tokenFilePath(userData), "utf8").trim();
      } catch {
        return { source: null, reason: "Alt\uB294 \uC2E4\uD589 \uC911\uC774\uC9C0\uB9CC \uB85C\uCEEC API \uD1A0\uD070 \uD30C\uC77C\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4." };
      }
      if (!token)
        return { source: null, reason: "Alt \uB85C\uCEEC API \uD1A0\uD070 \uD30C\uC77C\uC774 \uBE44\uC5B4 \uC788\uC2B5\uB2C8\uB2E4." };
      return {
        source: new _AltLocalApiSource({ port: p, token, version: status.version, openPathDb: opts.openPathDb, verifyOwner: verify, ownerPid: owner.pid, now: opts.now }),
        reason: ""
      };
    }
    if (refused)
      return { source: null, reason: `\uB85C\uCEEC API\uAC00 Alt\uC778\uC9C0 \uD655\uC778\uD558\uC9C0 \uBABB\uD574 \uD1A0\uD070\uC744 \uBCF4\uB0B4\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4: ${refused}` };
    return {
      source: null,
      reason: enabled === false ? "Alt \uC124\uC815\uC5D0\uC11C \uB85C\uCEEC HTTP \uC11C\uBC84\uAC00 \uAEBC\uC838 \uC788\uC2B5\uB2C8\uB2E4." : "Alt\uAC00 \uC2E4\uD589 \uC911\uC774 \uC544\uB2C8\uAC70\uB098 \uB85C\uCEEC API\uAC00 \uC751\uB2F5\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4."
    };
  }
  /**
   * Before a request batch: when the last owner check is `maxAgeMs` old or
   * older, check again, and require the same pid as approved. On failure
   * nothing is sent and the source is marked failed.
   */
  async ensureOwner(maxAgeMs) {
    if (this.failed)
      throw new AltApiError("Alt \uB85C\uCEEC API \uC5F0\uACB0\uC774 \uB04A\uACBC\uC2B5\uB2C8\uB2E4. \uB2E4\uC2DC \uC5F0\uACB0\uD558\uC138\uC694.", null);
    if (!this.verifyOwner || this.now() - this.lastOwnerCheck < maxAgeMs)
      return;
    const check = await this.verifyOwner(this.port);
    const samePid = check.pid !== void 0 && (this.ownerPid === null || check.pid === this.ownerPid);
    if (!check.ok || !samePid) {
      this.failed = true;
      throw new AltApiError(`\uB85C\uCEEC API \uD3EC\uD2B8\uC758 \uD504\uB85C\uADF8\uB7A8\uC774 \uBC14\uB00C\uC5B4 \uD1A0\uD070\uC744 \uBCF4\uB0B4\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4${check.ok ? "" : `: ${check.reason}`}`, null);
    }
    this.lastOwnerCheck = this.now();
  }
  async get(path) {
    let res;
    try {
      res = await request2(this.port, path, this.token, this.timeoutMs);
    } catch (e) {
      this.failed = true;
      throw new AltApiError(`Alt \uB85C\uCEEC API\uC5D0 \uC5F0\uACB0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${e instanceof Error ? e.message : String(e)}`, null);
    }
    if (res.status === 401)
      throw new AltApiError("Alt \uB85C\uCEEC API\uAC00 \uD1A0\uD070\uC744 \uAC70\uBD80\uD588\uC2B5\uB2C8\uB2E4. Alt\uB97C \uB2E4\uC2DC \uC2DC\uC791\uD55C \uB4A4 \uC0C8\uB85C\uACE0\uCE68\uD558\uC138\uC694.", 401);
    let json;
    try {
      json = JSON.parse(res.body);
    } catch {
      throw new AltApiError(`Alt \uB85C\uCEEC API \uC751\uB2F5\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (HTTP ${res.status})`, res.status);
    }
    if (res.status !== 200 || json.ok !== true) {
      throw new AltApiError(`Alt \uB85C\uCEEC API \uC624\uB958 (HTTP ${res.status}): ${typeof json.error === "string" ? json.error : "\uC54C \uC218 \uC5C6\uC74C"}`, res.status);
    }
    return json.data;
  }
  async folderMap(refresh = false) {
    if (this.folders && !refresh)
      return this.folders;
    const map = /* @__PURE__ */ new Map();
    flattenFolders(await this.get("/api/folders/tree"), map);
    this.folders = map;
    return map;
  }
  async listNotes() {
    await this.ensureOwner(0);
    const [rows, folders] = await Promise.all([this.get("/api/lectureNotes"), this.folderMap(true)]);
    if (!Array.isArray(rows))
      throw new AltApiError("Alt \uB85C\uCEEC API\uC758 \uB178\uD2B8 \uBAA9\uB85D \uD615\uC2DD\uC774 \uC608\uC0C1\uACFC \uB2E4\uB985\uB2C8\uB2E4.", 200);
    return rows.filter((r) => r && typeof r.id === "string").map((r) => toSummary(r, folders));
  }
  async components(id) {
    const raw = await this.get(`/api/noteComponents/note/${encodeURIComponent(id)}`);
    if (!Array.isArray(raw))
      throw new AltApiError("Alt \uB85C\uCEEC API\uC758 \uCEF4\uD3EC\uB10C\uD2B8 \uD615\uC2DD\uC774 \uC608\uC0C1\uACFC \uB2E4\uB985\uB2C8\uB2E4.", 200);
    return raw.map(componentFromApi);
  }
  /** Components, with the slides path filled in from the database for synced files. */
  async componentsWithPaths(id) {
    const components = await this.components(id);
    const slides = pickSlides(components);
    if (slides && !slides.file_path && slides.file_ref_id && this.openPathDb) {
      if (!this.pathMemo.has(id)) {
        let path = null;
        try {
          this.pathDb ??= this.openPathDb();
          path = (await this.pathDb.noteDetails(id)).pdfPath;
        } catch (e) {
          console.warn("[Alt2Obsidian] slides path lookup in the database failed:", e);
        }
        this.pathMemo.set(id, path);
      }
      slides.file_path = this.pathMemo.get(id) ?? null;
    }
    return components;
  }
  async noteDetails(id) {
    await this.ensureOwner(OWNER_RECHECK_MS);
    return detailsFromComponents(await this.componentsWithPaths(id));
  }
  close() {
    this.pathDb?.close?.();
    this.pathDb = null;
  }
  async getBundle(id) {
    await this.ensureOwner(0);
    const note = await this.get(`/api/lectureNotes/${encodeURIComponent(id)}`);
    if (!note || typeof note.id !== "string")
      throw new AltApiError("Alt\uC5D0\uC11C \uC774 \uB178\uD2B8\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.", 404);
    const [folders, components] = await Promise.all([this.folderMap(), this.componentsWithPaths(id)]);
    return bundleFromRows({
      note,
      folders,
      components,
      readFile: async (p) => {
        const buf = await readFile(p);
        return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
      }
    });
  }
};

// src/sources/AltLocalDbSource.ts
import { copyFileSync, constants, existsSync as existsSync2, mkdtempSync, readdirSync as readdirSync3, rmSync, statSync as statSync2 } from "node:fs";
import { readFile as readFile2 } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join as join3 } from "node:path";
var KNOWN_SCHEMA_VERSIONS = [40];
var REQUIRED_COLUMNS = {
  lecture_notes: ["id", "folder_id", "title", "lecture_date", "type", "updated_at", "deleted_at"],
  folders: ["id", "name", "parent_id", "deleted_at"],
  note_components: ["id", "note_id", "component_type", "title", "content_text", "metadata", "display_order", "file_inode", "deleted_at"],
  file_metadata: ["inode", "file_path"]
};
var AltDbError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "AltDbError";
  }
};
function loadSqlite() {
  const proc = process;
  try {
    const mod = proc.getBuiltinModule?.("node:sqlite");
    if (mod)
      return mod;
  } catch {
  }
  const req = globalThis.require;
  if (typeof req === "function") {
    try {
      return req("node:sqlite");
    } catch {
    }
  }
  throw new AltDbError(
    "\uC774 Obsidian\uC5D0\uB294 \uB0B4\uC7A5 SQLite(node:sqlite)\uAC00 \uC5C6\uC5B4 Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uC77D\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. Obsidian \uC124\uCE58 \uD30C\uC77C\uC744 \uCD5C\uC2E0\uC73C\uB85C \uBC1B\uAC70\uB098, Alt\uB97C \uC2E4\uD589\uD574 \uB85C\uCEEC API\uB85C \uAC00\uC838\uC624\uC138\uC694."
  );
}
function checkSchema(db) {
  const missing = [];
  for (const [table, cols] of Object.entries(REQUIRED_COLUMNS)) {
    const have = new Set(db.prepare(`SELECT name FROM pragma_table_info('${table}')`).all().map((r) => r.name));
    if (have.size === 0) {
      missing.push(`${table} \uD14C\uC774\uBE14`);
      continue;
    }
    for (const c of cols)
      if (!have.has(c))
        missing.push(`${table}.${c}`);
  }
  let version = null;
  try {
    const row = db.prepare("SELECT MAX(version) AS v FROM migrations").get();
    version = typeof row?.v === "number" ? row.v : null;
  } catch {
    version = null;
  }
  if (missing.length > 0) {
    throw new AltDbError(
      `\uC54C \uC218 \uC5C6\uB294 Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC2A4\uD0A4\uB9C8\uC785\uB2C8\uB2E4 (\uBC84\uC804 ${version ?? "?"}, \uC5C6\uB294 \uD56D\uBAA9: ${missing.slice(0, 6).join(", ")}). Alt\uB97C \uC2E4\uD589\uD574 \uB85C\uCEEC API\uB85C \uAC00\uC838\uC624\uC138\uC694.`
    );
  }
  return { version, known: version !== null && KNOWN_SCHEMA_VERSIONS.includes(version) };
}
function hasColumn(db, table, column) {
  return db.prepare(`SELECT name FROM pragma_table_info('${table}')`).all().some((r) => r.name === column);
}
var SCOPE_TABLES = ["channel_members", "channels", "workspace_members", "workspaces", "workspace_access_snapshot", "workspace_access_snapshot_state"];
function activeContentSql(alias, accountId, support) {
  const active = `${alias}.deleted_at IS NULL`;
  if (accountId === void 0 || support === "none")
    return active;
  const space = `${alias}.channel_id`;
  if (accountId === null || support === "channel-only")
    return `${active} AND ${space} IS NULL`;
  const actor = `'${accountId.replace(/'/g, "''")}'`;
  const snapshot = `(NOT EXISTS(SELECT 1 FROM workspace_access_snapshot_state) OR ${space} IN (SELECT id FROM workspace_access_snapshot WHERE kind='team'))`;
  return `${active} AND (${space} IS NULL OR (${snapshot} AND ${space} IN (
    SELECT tm.channel_id FROM channel_members tm JOIN channels t ON t.id=tm.channel_id
    WHERE tm.user_id=${actor} AND t.deleted_at IS NULL AND t.archived_at IS NULL
    AND (t.workspace_id IS NULL OR t.workspace_id IN (
      SELECT wm.workspace_id FROM workspace_members wm JOIN workspaces w ON w.id=wm.workspace_id
      WHERE wm.user_id=${actor} AND wm.status='active' AND w.deleted_at IS NULL
    ))
  )))`;
}
var STALE_COPY_MS = 60 * 60 * 1e3;
function sweepStaleCopies(tmpRoot, now = Date.now()) {
  let removed = 0;
  let names = [];
  try {
    names = readdirSync3(tmpRoot);
  } catch {
    return 0;
  }
  for (const n of names) {
    if (!n.startsWith("alt2obs-altdb-"))
      continue;
    const p = join3(tmpRoot, n);
    try {
      if (now - statSync2(p).mtimeMs > STALE_COPY_MS) {
        rmSync(p, { recursive: true, force: true });
        removed++;
      }
    } catch {
    }
  }
  return removed;
}
var AltLocalDbSource = class _AltLocalDbSource {
  constructor(db, copyDir, schema, storeName, hasFileRefs) {
    this.db = db;
    this.copyDir = copyDir;
    this.hasFileRefs = hasFileRefs;
    this.mode = "db";
    /** Status detail naming the store when the signed-in account is unknown ("" otherwise). */
    this.storeDetail = "";
    this.accountId = void 0;
    this.support = "none";
    this.schema = schema;
    this.storeName = storeName;
    this.label = `Alt \uAEBC\uC9D0 \xB7 DB \uC77D\uAE30${schema.known ? "" : ` (\uD655\uC778\uB418\uC9C0 \uC54A\uC740 \uC2A4\uD0A4\uB9C8 v${schema.version ?? "?"})`}`;
  }
  setScope(c, userKnown) {
    this.accountId = c.accountId;
    const channels = ["lecture_notes", "folders", "note_components"].every((t) => hasColumn(this.db, t, "channel_id"));
    this.support = !channels ? "none" : SCOPE_TABLES.every((t) => this.tableExists(t)) ? "full" : "channel-only";
    if (!userKnown)
      this.storeDetail = `\uB85C\uADF8\uC778 \uACC4\uC815\uC744 \uC54C \uC218 \uC5C6\uC5B4 \uAC00\uC7A5 \uCD5C\uADFC \uC800\uC7A5\uC18C\uB97C \uC77D\uC5C8\uC2B5\uB2C8\uB2E4: ${this.storeName}`;
  }
  tableExists(name) {
    return !!this.db.prepare("SELECT 1 AS x FROM sqlite_master WHERE type IN ('table','view') AND name = ?").get(name);
  }
  scope(alias) {
    return activeContentSql(alias, this.accountId, this.support);
  }
  /**
   * Copies the best store (signed-in account first) to a temp folder and
   * opens the copy. A store without notes is skipped when another has some.
   */
  static open(opts) {
    const candidates = dbCandidates(opts.userData);
    if (candidates.length === 0)
      throw new AltDbError("Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. Alt\uAC00 \uC774 \uCEF4\uD4E8\uD130\uC5D0 \uC124\uCE58\uB418\uC5B4 \uC788\uB294\uC9C0 \uD655\uC778\uD558\uC138\uC694.");
    const userKnown = activeProfileUserId(opts.userData) !== null;
    sweepStaleCopies(opts.tmpRoot ?? tmpdir());
    const sqlite = opts.sqlite ?? loadSqlite();
    let fallback = null;
    let lastError = null;
    for (const candidate of candidates) {
      const file = candidate.path;
      let source;
      try {
        source = _AltLocalDbSource.openCopy(file, sqlite, opts.tmpRoot ?? tmpdir());
        source.setScope(candidate, userKnown);
      } catch (e) {
        if (e instanceof AltDbError) {
          fallback?.close();
          throw e;
        }
        if (file === candidates[0].path) {
          throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC0AC\uBCF8\uC744 \uC5F4\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${basename(file)}): ${e instanceof Error ? e.message : String(e)}. \uC7A0\uC2DC \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC138\uC694.`);
        }
        lastError = e;
        continue;
      }
      let count;
      try {
        count = source.noteCount();
      } catch (e) {
        source.close();
        fallback?.close();
        throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC0AC\uBCF8\uC744 \uC77D\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (${basename(file)}): ${e instanceof Error ? e.message : String(e)}. \uC7A0\uC2DC \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD558\uC138\uC694.`);
      }
      if (count > 0) {
        fallback?.close();
        return source;
      }
      if (!fallback)
        fallback = source;
      else
        source.close();
    }
    if (fallback)
      return fallback;
    throw new AltDbError(`Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uB97C \uC5F4\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${lastError instanceof Error ? lastError.message : String(lastError)}`);
  }
  static openCopy(file, sqlite, tmpRoot) {
    const dir = mkdtempSync(join3(tmpRoot, "alt2obs-altdb-"));
    try {
      const target = join3(dir, basename(file));
      copyFileSync(file, target, constants.COPYFILE_FICLONE);
      if (existsSync2(`${file}-wal`))
        copyFileSync(`${file}-wal`, `${target}-wal`, constants.COPYFILE_FICLONE);
      const db = new sqlite.DatabaseSync(target);
      try {
        db.exec("PRAGMA query_only = 1");
        const schema = checkSchema(db);
        return new _AltLocalDbSource(db, dir, schema, basename(file), hasColumn(db, "note_components", "file_ref_id"));
      } catch (e) {
        db.close();
        throw e;
      }
    } catch (e) {
      rmSync(dir, { recursive: true, force: true });
      throw e;
    }
  }
  noteCount() {
    const row = this.db.prepare(`SELECT COUNT(*) AS c FROM lecture_notes ln WHERE ${this.scope("ln")}`).get();
    return row.c;
  }
  folderMap() {
    const rows = this.db.prepare(`SELECT f.id, f.name, f.parent_id FROM folders f WHERE ${this.scope("f")}`).all();
    return new Map(rows.map((r) => [r.id, { id: r.id, name: r.name, parent_id: r.parent_id }]));
  }
  async listNotes() {
    const folders = this.folderMap();
    const rows = this.db.prepare(`SELECT ln.id, ln.title, ln.type, ln.lecture_date, ln.folder_id, ln.updated_at FROM lecture_notes ln WHERE ${this.scope("ln")} ORDER BY ln.lecture_date DESC, ln.id DESC`).all();
    return rows.map((r) => toSummary(r, folders));
  }
  components(noteId) {
    const refPath = this.hasFileRefs ? `(SELECT COALESCE(NULLIF(fm2.file_path, ''), NULLIF(fl.local_cache_path, ''))
            FROM file_ref_local_files fl LEFT JOIN file_metadata fm2 ON fm2.inode = fl.file_inode
           WHERE fl.file_ref_id = nc.file_ref_id ORDER BY fl.updated_at DESC LIMIT 1)` : "NULL";
    const sql = `SELECT nc.id, nc.note_id, nc.component_type, nc.title, nc.content_text, nc.metadata, nc.display_order,
                        ${this.hasFileRefs ? "nc.file_ref_id" : "NULL"} AS file_ref_id,
                        COALESCE((SELECT NULLIF(fm.file_path, '') FROM file_metadata fm WHERE fm.inode = nc.file_inode LIMIT 1), ${refPath}) AS file_path
                   FROM note_components nc
                  WHERE nc.note_id = ? AND ${this.scope("nc")}
                  ORDER BY nc.display_order, nc.component_type, nc.title, nc.id`;
    try {
      return this.db.prepare(sql).all(noteId);
    } catch (e) {
      if (!this.hasFileRefs)
        throw e;
      this.hasFileRefs = false;
      return this.components(noteId);
    }
  }
  async noteDetails(id) {
    return detailsFromComponents(this.components(id));
  }
  async getBundle(id) {
    const note = this.db.prepare(`SELECT ln.id, ln.title, ln.type, ln.lecture_date, ln.folder_id, ln.updated_at FROM lecture_notes ln WHERE ln.id = ? AND ${this.scope("ln")}`).get(id);
    if (!note)
      throw new AltDbError("Alt \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uC5D0\uC11C \uC774 \uB178\uD2B8\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.");
    return bundleFromRows({
      note,
      folders: this.folderMap(),
      components: this.components(id),
      readFile: async (p) => {
        const buf = await readFile2(p);
        return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
      }
    });
  }
  close() {
    try {
      this.db.close();
    } catch {
    }
    rmSync(this.copyDir, { recursive: true, force: true });
  }
};

// src/sources/index.ts
async function connectAltLocal(userData, opts = {}) {
  const dbOpts = { userData, sqlite: opts.sqlite, tmpRoot: opts.tmpRoot };
  const api = await AltLocalApiSource.detect(userData, {
    probeTimeoutMs: opts.probeTimeoutMs,
    verifyOwner: opts.verifyOwner,
    // Synced slides: the API has no path for them; one DB copy per connect does.
    openPathDb: () => AltLocalDbSource.open(dbOpts)
  });
  if (api.source)
    return { source: api.source, label: api.source.label, detail: "" };
  try {
    const db = AltLocalDbSource.open(dbOpts);
    return { source: db, label: db.label, detail: [api.reason, db.storeDetail].filter(Boolean).join(" ") };
  } catch (e) {
    return { source: null, label: "\uC5F0\uACB0 \uC548 \uB428", detail: `${api.reason} ${e instanceof Error ? e.message : String(e)}`.trim() };
  }
}

// scripts/src/cli-common.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/alt-local.ts
function option(args, name) {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : void 0;
}
async function connect(userData, mode) {
  if (mode === "api") {
    const r = await AltLocalApiSource.detect(userData);
    return { source: r.source, label: r.source?.label ?? "\uC5F0\uACB0 \uC548 \uB428", detail: r.reason };
  }
  if (mode === "db") {
    const db = AltLocalDbSource.open({ userData });
    return { source: db, label: db.label, detail: "" };
  }
  return connectAltLocal(userData);
}
async function main() {
  const args = process.argv.slice(2);
  const pos = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("--"))
      i++;
    else
      pos.push(args[i]);
  }
  const cmd = pos[0];
  const userData = option(args, "--alt-dir") ?? altUserDataDir();
  const mode = option(args, "--source") ?? "auto";
  if (!["status", "list", "export"].includes(cmd) || !["auto", "api", "db"].includes(mode)) {
    process.stderr.write("Usage: node scripts/phase2/alt-local.mjs status | list [--query T] | export <noteId> [outDir] [--alt-dir DIR] [--source auto|api|db]\n");
    process.exit(2);
  }
  const conn = await connect(userData, mode);
  const source = conn.source;
  try {
    if (cmd === "status") {
      process.stdout.write(JSON.stringify({ mode: source?.mode ?? "none", label: conn.label, detail: conn.detail }) + "\n");
      return;
    }
    if (!source)
      throw new Error(`Alt\uC5D0 \uC5F0\uACB0\uD558\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4: ${conn.detail}`);
    if (cmd === "list") {
      const q = (option(args, "--query") ?? "").toLowerCase();
      const notes = (await source.listNotes()).filter((n) => !q || n.title.toLowerCase().includes(q) || n.folderPath.join("/").toLowerCase().includes(q)).map((n) => ({ id: n.id, title: n.title, type: n.type, lectureDate: n.lectureDate, folderPath: n.folderPath, subject: inferSubject(n.folderPath, n.title) }));
      process.stdout.write(JSON.stringify({ mode: source.mode, notes }) + "\n");
      return;
    }
    const [, id, outArg] = pos;
    if (!id)
      throw new Error("export needs <noteId>");
    const bundle = await source.getBundle(id);
    if (outArg)
      mkdirSync(outArg, { recursive: true });
    const outDir = mkdtempSync2(join4(outArg ?? tmpdir2(), "alt2obs-export-"));
    const { pdf: _pdf, ...rest } = bundle;
    const out = { ...rest, subject: inferSubject(bundle.folderPath ?? [], bundle.title) };
    const bundlePath = join4(outDir, "bundle.json");
    writeFileSync(bundlePath, JSON.stringify(out, null, 1), { mode: 384 });
    writeFileSync(join4(outDir, "transcript.txt"), bundle.transcript.map((s) => s.text).join("\n"), { mode: 384 });
    process.stdout.write(
      JSON.stringify({
        dir: outDir,
        bundle: bundlePath,
        pdfPath: bundle.pdf ? bundle.pdfPath : null,
        segments: bundle.transcript.length,
        timestamps: bundle.transcript.some((s) => s.startMs !== null),
        warnings: bundle.warnings ?? []
      }) + "\n"
    );
  } finally {
    source?.close?.();
  }
}
main().catch((e) => fail(e, "alt-local"));
