// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/merge-note.ts
import { readFile } from "node:fs/promises";

// src/types.ts
var MANAGED_NOTE_START = "<!-- alt2obsidian:start -->";
var MANAGED_NOTE_END = "<!-- alt2obsidian:end -->";
var OVERVIEW_BLOCK_START = "<!-- alt2obs:overview start -->";
var OVERVIEW_BLOCK_END = "<!-- alt2obs:overview end -->";

// src/core/merge.ts
var LEGACY_MIGRATION_NOTE = "\uAE30\uC874 \uB2E8\uC77C \uBE14\uB85D \uD615\uC2DD\uC5D0\uC11C \uD398\uC774\uC9C0\uBCC4 \uAD6C\uC870\uB85C \uB9C8\uC774\uADF8\uB808\uC774\uC158\uB429\uB2C8\uB2E4. \uAE30\uC874 \uB178\uD2B8 \uC804\uCCB4\uB294 \uB9E8 \uC544\uB798 '\uC774\uC804 \uB178\uD2B8 \uBC31\uC5C5'\uC5D0 \uBCF4\uAD00\uB429\uB2C8\uB2E4.";
function assertNoPageAnchoredDowngrade(currentContent, nextContent) {
  if (hasMultiManagedMarkers(currentContent) && !hasMultiManagedMarkers(nextContent)) {
    throw new Error(
      "\uAE30\uC874 \uB178\uD2B8\uB294 \uC2AC\uB77C\uC774\uB4DC\uBCC4 \uD615\uC2DD\uC778\uB370 \uC774\uBC88 \uACB0\uACFC\uC5D0\uB294 \uC2AC\uB77C\uC774\uB4DC\uBCC4 \uD574\uC124\uC774 \uC5C6\uC5B4 \uB36E\uC5B4\uC4F0\uC9C0 \uC54A\uACE0 \uAC00\uC838\uC624\uAE30\uB97C \uC911\uB2E8\uD588\uC2B5\uB2C8\uB2E4. PDF\uB97C \uB0B4\uB824\uBC1B\uAC70\uB098 \uC77D\uC9C0 \uBABB\uD588\uAC70\uB098, \uD604\uC7AC LLM \uACF5\uAE09\uC790\uAC00 \uC774\uBBF8\uC9C0 \uC785\uB825(\uBA40\uD2F0\uBAA8\uB2EC)\uC744 \uC9C0\uC6D0\uD558\uC9C0 \uC54A\uB294 \uACBD\uC6B0\uC785\uB2C8\uB2E4. PDF \uC811\uADFC\uACFC LLM \uACF5\uAE09\uC790 \uC124\uC815(Gemini \uAD8C\uC7A5)\uC744 \uD655\uC778\uD55C \uB4A4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574\uC8FC\uC138\uC694."
    );
  }
}
function mergeManagedNote(currentContent, nextContent) {
  const nextParts = splitManagedNote(nextContent);
  const currentParts = splitManagedNote(currentContent);
  if (currentParts.managed) {
    return [
      nextParts.frontmatter,
      currentParts.before.trim(),
      nextParts.managed,
      currentParts.after.trim()
    ].filter(Boolean).join("\n\n").trimEnd() + "\n";
  }
  return appendPreviousNoteBackup(currentContent, nextContent, { skipIfBackupExists: true });
}
function appendPreviousNoteBackup(currentContent, nextContent, opts) {
  const hasExistingBackup = /(^|\n)## 이전 노트 백업\s*\n/.test(currentContent);
  if (opts.skipIfBackupExists && hasExistingBackup || currentContent.trim().length === 0) {
    return nextContent;
  }
  return [
    nextContent.trimEnd(),
    "",
    "## \uC774\uC804 \uB178\uD2B8 \uBC31\uC5C5",
    "",
    "> [!note]",
    "> \uC774 \uB0B4\uC6A9\uC740 Alt2Obsidian \uAD00\uB9AC \uAD6C\uAC04\uC774 \uB3C4\uC785\uB418\uAE30 \uC804\uC758 \uAE30\uC874 \uB178\uD2B8\uC785\uB2C8\uB2E4.",
    "",
    currentContent.trim(),
    ""
  ].join("\n");
}
function splitManagedNote(content) {
  const frontmatterMatch = content.match(/^---\n[\s\S]*?\n---\n*/);
  const frontmatter = frontmatterMatch ? frontmatterMatch[0].trimEnd() : "";
  const contentStart = frontmatterMatch ? frontmatterMatch[0].length : 0;
  const start = content.indexOf(MANAGED_NOTE_START);
  const end = content.indexOf(MANAGED_NOTE_END);
  if (start === -1 || end === -1 || end < start) {
    return { frontmatter, before: "", managed: "", after: "" };
  }
  const managedEnd = end + MANAGED_NOTE_END.length;
  return {
    frontmatter,
    before: content.slice(contentStart, start),
    managed: content.slice(start, managedEnd).trimEnd(),
    after: content.slice(managedEnd)
  };
}
function hasMultiManagedMarkers(content) {
  return /<!-- alt2obs:slide:\d+ hash:[0-9a-f]{8}(?: dup:\d+)? (start|end) -->/.test(
    content
  );
}
function splitMultiManagedNote(content) {
  const fmMatch = content.match(/^---\n[\s\S]*?\n---\n*/);
  const frontmatter = fmMatch ? fmMatch[0] : "";
  const body = fmMatch ? content.slice(fmMatch[0].length) : content;
  const markers = [];
  const re = /<!-- alt2obs:slide:(\d+) hash:([0-9a-f]{8})(?: dup:(\d+))? (start|end) -->/g;
  let m;
  while ((m = re.exec(body)) !== null) {
    markers.push({
      idx: m.index,
      end: m.index + m[0].length,
      slideNum: parseInt(m[1], 10),
      hash: m[2],
      dup: m[3] ? parseInt(m[3], 10) : void 0,
      type: m[4]
    });
  }
  const sections = [];
  const sectionRanges = [];
  const used = /* @__PURE__ */ new Set();
  for (let i = 0; i < markers.length; i++) {
    const s = markers[i];
    if (s.type !== "start" || used.has(i))
      continue;
    let pairIdx = -1;
    for (let k = i + 1; k < markers.length; k++) {
      const e2 = markers[k];
      if (e2.type === "end" && !used.has(k) && e2.slideNum === s.slideNum && e2.hash === s.hash && e2.dup === s.dup) {
        pairIdx = k;
        break;
      }
    }
    if (pairIdx < 0)
      continue;
    used.add(i);
    used.add(pairIdx);
    const e = markers[pairIdx];
    sections.push({
      slideNum: s.slideNum,
      hash: s.hash,
      dup: s.dup,
      managed: body.slice(s.end, e.idx),
      after: ""
    });
    sectionRanges.push({ startIdx: s.idx, endIdxAfterMarker: e.end });
  }
  if (sections.length === 0) {
    return { frontmatter, preamble: body, sections: [] };
  }
  let preamble = body.slice(0, sectionRanges[0].startIdx);
  const slideH2 = preamble.match(/(^|\n)## 📚 슬라이드 \d+/);
  if (slideH2 && slideH2.index !== void 0) {
    const cutAt = slideH2.index + (slideH2[1] === "\n" ? 1 : 0);
    preamble = preamble.slice(0, cutAt);
  }
  for (let i = 0; i < sections.length; i++) {
    const range = sectionRanges[i];
    const fromIdx = range.endIdxAfterMarker;
    const nextRange = sectionRanges[i + 1];
    const candidateEnd = nextRange ? nextRange.startIdx : body.length;
    const slice = body.slice(fromIdx, candidateEnd);
    const nextH2 = slice.search(/(^|\n)## 📚 슬라이드 \d+/);
    if (nextH2 >= 0) {
      const cutAt = nextH2 + (slice[nextH2] === "\n" ? 1 : 0);
      sections[i].after = slice.slice(0, cutAt);
    } else {
      sections[i].after = slice;
    }
  }
  return { frontmatter, preamble, sections };
}
function formatSlideMarker(slideNum, hash, dup, kind) {
  const dupSuffix = dup !== void 0 ? ` dup:${dup}` : "";
  return `<!-- alt2obs:slide:${slideNum} hash:${hash}${dupSuffix} ${kind} -->`;
}
function mergeMultiManagedNote(existingContent, nextContent) {
  const existing = splitMultiManagedNote(existingContent);
  const next = splitMultiManagedNote(nextContent);
  if (existing.sections.length === 0) {
    return {
      merged: appendPreviousNoteBackup(existingContent, nextContent, { skipIfBackupExists: false }),
      reorders: [],
      insertions: next.sections.map((s) => s.slideNum),
      deletions: [],
      drifts: [],
      confirmDeckReplacement: false,
      notes: existingContent.trim() ? [LEGACY_MIGRATION_NOTE] : []
    };
  }
  const used = /* @__PURE__ */ new Set();
  const matched = /* @__PURE__ */ new Map();
  const reorders = [];
  const insertions = [];
  const deletions = [];
  const drifts = [];
  const buckets = /* @__PURE__ */ new Map();
  for (const s of existing.sections) {
    if (!buckets.has(s.hash))
      buckets.set(s.hash, []);
    buckets.get(s.hash).push(s);
  }
  next.sections.forEach((ns, i) => {
    const candidates = buckets.get(ns.hash) ?? [];
    for (const c of candidates) {
      const idx = existing.sections.indexOf(c);
      if (!used.has(idx)) {
        used.add(idx);
        matched.set(i, c);
        if (c.slideNum !== ns.slideNum) {
          reorders.push({ from: c.slideNum, to: ns.slideNum, hash: ns.hash });
        }
        break;
      }
    }
  });
  next.sections.forEach((ns, i) => {
    if (matched.has(i))
      return;
    const idx = existing.sections.findIndex(
      (s, j) => !used.has(j) && s.slideNum === ns.slideNum
    );
    if (idx >= 0) {
      used.add(idx);
      matched.set(i, existing.sections[idx]);
      drifts.push({
        slideNum: ns.slideNum,
        oldHash: existing.sections[idx].hash,
        newHash: ns.hash
      });
    }
  });
  next.sections.forEach((ns, i) => {
    if (!matched.has(i))
      insertions.push(ns.slideNum);
  });
  for (let i = 0; i < existing.sections.length; i++) {
    if (!used.has(i)) {
      deletions.push({
        slideNum: existing.sections[i].slideNum,
        hash: existing.sections[i].hash
      });
    }
  }
  const confirmDeckReplacement = existing.sections.length > 0 && deletions.length > 0.5 * existing.sections.length;
  const sectionMarkdown = next.sections.map((ns, i) => {
    const cand = matched.get(i);
    const startMarker = formatSlideMarker(ns.slideNum, ns.hash, ns.dup, "start");
    const endMarker = formatSlideMarker(ns.slideNum, ns.hash, ns.dup, "end");
    const after = cand && cand.after.trim().length > 0 ? cand.after : "\n\n> [!note] \uB0B4 \uBA54\uBAA8\n> \n\n";
    return [
      `## \u{1F4DA} \uC2AC\uB77C\uC774\uB4DC ${ns.slideNum}`,
      "",
      startMarker,
      ns.managed.trim(),
      endMarker,
      after.startsWith("\n") ? after.slice(1) : after
    ].join("\n");
  }).join("\n");
  let orphanFooter = "";
  if (deletions.length > 0) {
    const orphanBlocks = existing.sections.map((s, i) => used.has(i) ? null : s).filter((s) => s !== null).map((s) => {
      const dupSuffix = s.dup !== void 0 ? ` dup:${s.dup}` : "";
      const orphanMarker = `<!-- alt2obs:orphan slide:${s.slideNum} hash:${s.hash}${dupSuffix} -->`;
      return `${orphanMarker}
${s.after.trim()}`;
    }).join("\n\n");
    orphanFooter = `

## \u{1F5D1}\uFE0F \uC0AD\uC81C\uB41C \uC2AC\uB77C\uC774\uB4DC (orphan)

${orphanBlocks}
`;
  }
  const { preamble, notes } = mergeOverviewPreamble(existing.preamble, next.preamble);
  const merged = next.frontmatter + preamble + sectionMarkdown + orphanFooter;
  return { merged, reorders, insertions, deletions, drifts, confirmDeckReplacement, notes };
}
function mergeOverviewPreamble(existingPreamble, nextPreamble) {
  const nextSection = extractOverviewSection(nextPreamble);
  const existingStart = existingPreamble.indexOf(OVERVIEW_BLOCK_START);
  if (!nextSection) {
    const notes = existingStart >= 0 ? ["\uC0C8 \uC694\uC57D\uC774 \uBE44\uC5B4 \uC788\uC5B4 \uAE30\uC874 \uC804\uCCB4 \uC694\uC57D\uC744 \uADF8\uB300\uB85C \uB450\uC5C8\uC2B5\uB2C8\uB2E4. \uCD5C\uC2E0 \uB0B4\uC6A9\uC774 \uC544\uB2D0 \uC218 \uC788\uC2B5\uB2C8\uB2E4."] : [];
    return { preamble: existingPreamble, notes };
  }
  const existingBlock = findOverviewBlock(existingPreamble);
  const nextBlock = findOverviewBlock(nextPreamble);
  if (existingBlock) {
    return {
      preamble: existingPreamble.slice(0, existingBlock.bodyStart) + nextPreamble.slice(nextBlock.bodyStart, nextBlock.bodyEnd) + existingPreamble.slice(existingBlock.bodyEnd),
      notes: []
    };
  }
  if (existingStart >= 0) {
    const heading = existingPreamble.lastIndexOf(OVERVIEW_HEADING, existingStart);
    const cut = heading >= 0 ? heading : existingStart;
    return {
      preamble: withBlankLineAfter(existingPreamble.slice(0, cut)) + nextSection,
      notes: []
    };
  }
  const title = existingPreamble.match(/^# .*(\n|$)/m);
  if (title && title.index !== void 0) {
    const head = existingPreamble.slice(0, title.index + title[0].length);
    const rest = existingPreamble.slice(head.length).replace(/^\n+/, "");
    return { preamble: withBlankLineAfter(head) + nextSection + rest, notes: [] };
  }
  return { preamble: withBlankLineAfter(existingPreamble) + nextSection, notes: [] };
}
var OVERVIEW_HEADING = "## \u{1F4CB} \uC804\uCCB4 \uC694\uC57D";
function extractOverviewSection(preamble) {
  const block = findOverviewBlock(preamble);
  if (!block)
    return null;
  const heading = preamble.lastIndexOf(OVERVIEW_HEADING, block.bodyStart);
  const from = heading >= 0 ? heading : preamble.indexOf(OVERVIEW_BLOCK_START);
  return preamble.slice(from, block.bodyEnd + OVERVIEW_BLOCK_END.length) + "\n\n";
}
function withBlankLineAfter(text) {
  const trimmed = text.replace(/\n+$/, "");
  return trimmed.length > 0 ? `${trimmed}

` : "";
}
function findOverviewBlock(text) {
  const start = text.indexOf(OVERVIEW_BLOCK_START);
  if (start < 0)
    return null;
  const bodyStart = start + OVERVIEW_BLOCK_START.length;
  const bodyEnd = text.indexOf(OVERVIEW_BLOCK_END, bodyStart);
  if (bodyEnd < 0)
    return null;
  return { bodyStart, bodyEnd };
}
function mergeNote(currentContent, nextContent) {
  assertNoPageAnchoredDowngrade(currentContent, nextContent);
  if (hasMultiManagedMarkers(nextContent) || hasMultiManagedMarkers(currentContent)) {
    return { mode: "multi", ...mergeMultiManagedNote(currentContent, nextContent) };
  }
  return {
    merged: mergeManagedNote(currentContent, nextContent),
    mode: "legacy",
    reorders: [],
    insertions: [],
    deletions: [],
    drifts: [],
    confirmDeckReplacement: false,
    notes: []
  };
}

// scripts/src/cli-common.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/merge-note.ts
async function main() {
  const args = process.argv.slice(2);
  const summaryOnly = args.includes("--summary");
  const [existingPath, nextPath] = args.filter((a) => a !== "--summary");
  if (!existingPath || !nextPath) {
    process.stderr.write("Usage: node scripts/phase2/merge-note.mjs <existingNote> <newNote> [--summary]\n");
    process.exit(2);
  }
  const result = mergeNote(await readFile(existingPath, "utf8"), await readFile(nextPath, "utf8"));
  if (summaryOnly) {
    const { merged: _merged, ...summary } = result;
    process.stdout.write(JSON.stringify(summary) + "\n");
  } else {
    process.stdout.write(result.merged);
  }
}
main().catch((e) => fail(e, "merge-note"));
