// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/overview-block.ts
import { readFile } from "node:fs/promises";

// src/types.ts
var OVERVIEW_BLOCK_START = "<!-- alt2obs:overview start -->";
var OVERVIEW_BLOCK_END = "<!-- alt2obs:overview end -->";

// src/core/markdown.ts
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function linkConceptNames(text, conceptNames) {
  const names = Array.from(
    new Set(conceptNames.map((n) => n.trim()).filter((n) => n.length > 0))
  ).sort((a, b) => b.length - a.length);
  if (names.length === 0)
    return text;
  const canonical = /* @__PURE__ */ new Map();
  for (const name of names) {
    const key = name.toLowerCase();
    if (!canonical.has(key))
      canonical.set(key, name);
  }
  const pattern = new RegExp(names.map(escapeRegex).join("|"), "gi");
  const link = (segment) => segment.replace(pattern, (m) => `[[${canonical.get(m.toLowerCase()) ?? m}]]`);
  return text.split(/(\[\[[^\]\n]*\]\])/).map((part, i) => i % 2 === 1 ? part : link(part)).join("");
}
function demoteHeadings(markdown) {
  let fence = null;
  return markdown.split("\n").map((line) => {
    const fenceMatch = line.match(/^\s{0,3}(`{3,}|~{3,})/);
    if (fenceMatch) {
      const marker = fenceMatch[1][0];
      if (fence === null)
        fence = marker;
      else if (fence === marker)
        fence = null;
      return line;
    }
    if (fence !== null)
      return line;
    return /^#{1,5}(\s|$)/.test(line) ? `#${line}` : line;
  }).join("\n");
}
function buildOverviewSection(summary, conceptNames) {
  const trimmed = (summary || "").trim();
  if (trimmed.length === 0)
    return "";
  const body = linkConceptNames(demoteHeadings(trimmed), conceptNames);
  return [
    "## \u{1F4CB} \uC804\uCCB4 \uC694\uC57D",
    "",
    OVERVIEW_BLOCK_START,
    body,
    OVERVIEW_BLOCK_END,
    "",
    ""
  ].join("\n");
}

// scripts/src/node-pdf.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/overview-block.ts
async function main() {
  const [summaryFile, namesFile] = process.argv.slice(2);
  if (!summaryFile) {
    process.stderr.write("Usage: node scripts/phase2/overview-block.mjs <summaryFile> [conceptNamesJsonFile]\n");
    process.exit(2);
  }
  const summary = await readFile(summaryFile, "utf8");
  const names = namesFile ? JSON.parse(await readFile(namesFile, "utf8")) : [];
  if (!Array.isArray(names) || !names.every((n) => typeof n === "string")) {
    throw new Error("concept names file must be a JSON array of strings");
  }
  process.stdout.write(buildOverviewSection(summary, names));
}
main().catch((e) => fail(e, "overview-block"));
