// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/overview-block.ts
import { readFile } from "node:fs/promises";

// src/types.ts
var DEFAULT_GENERATION = {
  batchSize: 8,
  imageRule: "auto",
  transcriptCapChars: 600,
  tokenCapPerLecture: 0,
  saveKeyDiagrams: true,
  onlyChangedSlides: true
};
var TASK_DEFAULTS = {
  "claude-cli": {
    commentary: { model: "sonnet", effort: "medium" },
    concepts: { model: "haiku", effort: "low" },
    alignment: { model: "haiku", effort: "low" },
    verification: { model: "sonnet", effort: "medium" }
  },
  "codex-cli": {
    commentary: { model: "", effort: "medium" },
    concepts: { model: "", effort: "low" },
    alignment: { model: "", effort: "low" },
    verification: { model: "", effort: "medium" }
  }
};
var CLAUDE_TASK_DEFAULTS = {
  commentary: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].commentary },
  concepts: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].concepts },
  alignment: { provider: "none", model: "", effort: "" },
  verification: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].verification }
};
var DEFAULT_SETTINGS = {
  baseFolderPath: "Alt2Obsidian",
  language: "ko",
  settingsVersion: 3,
  claudePath: "",
  codexPath: "",
  cliTimeoutSec: 300,
  tasks: CLAUDE_TASK_DEFAULTS,
  preset: "custom",
  recentModels: {},
  generation: DEFAULT_GENERATION,
  altDataDir: "",
  notionFetchTool: "",
  hideManagedComments: true
};
var EMPTY_USAGE = {
  calls: 0,
  inputTokens: 0,
  cachedInputTokens: 0,
  outputTokens: 0,
  imagesSent: 0,
  costUsd: 0
};
var DEFAULT_PLUGIN_DATA = {
  settings: DEFAULT_SETTINGS,
  recentImports: [],
  cliDetection: {},
  usageTotals: { ...EMPTY_USAGE, lectures: 0, byProvider: {}, since: "" }
};
var OVERVIEW_BLOCK_START = "<!-- alt2obs:overview start -->";
var OVERVIEW_BLOCK_END = "<!-- alt2obs:overview end -->";

// src/core/markdown.ts
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function linkConceptNames(text, conceptNames) {
  const names = Array.from(
    new Set(conceptNames.map((n) => n.trim()).filter((n) => n.length > 0))
  ).sort((a, b) => b.length - a.length);
  if (names.length === 0)
    return text;
  const canonical = /* @__PURE__ */ new Map();
  for (const name of names) {
    const key = name.toLowerCase();
    if (!canonical.has(key))
      canonical.set(key, name);
  }
  const pattern = new RegExp(names.map(escapeRegex).join("|"), "gi");
  const link = (segment) => segment.replace(pattern, (m) => `[[${canonical.get(m.toLowerCase()) ?? m}]]`);
  return text.split(/(\[\[[^\]\n]*\]\])/).map((part, i) => i % 2 === 1 ? part : link(part)).join("");
}
function demoteHeadings(markdown) {
  const out = [];
  let fence = null;
  let paragraphLines = 0;
  for (const line of markdown.split("\n")) {
    const fenceMatch = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (fence) {
      if (fenceMatch && fenceMatch[1][0] === fence.char && fenceMatch[1].length >= fence.len && fenceMatch[2].trim() === "") {
        fence = null;
      }
      out.push(line);
      continue;
    }
    if (fenceMatch && !(fenceMatch[1][0] === "`" && fenceMatch[2].includes("`"))) {
      fence = { char: fenceMatch[1][0], len: fenceMatch[1].length };
      out.push(line);
      paragraphLines = 0;
      continue;
    }
    const setext = line.match(/^ {0,3}(=+|-+)[ \t]*$/);
    if (setext && paragraphLines > 0) {
      const text = out.splice(out.length - paragraphLines, paragraphLines).map((l) => l.trim()).join(" ");
      out.push(`${setext[1][0] === "=" ? "##" : "###"} ${text}`);
      paragraphLines = 0;
      continue;
    }
    const atx = line.match(/^( {0,3})(#{1,6})(?=[ \t]|$)/);
    if (atx) {
      out.push(atx[2].length < 6 ? `${atx[1]}#${line.slice(atx[1].length)}` : line);
      paragraphLines = 0;
      continue;
    }
    out.push(line);
    paragraphLines = isParagraphLine(line) ? paragraphLines + 1 : 0;
  }
  return out.join("\n");
}
function isParagraphLine(line) {
  if (line.trim() === "")
    return false;
  if (/^ {4,}/.test(line))
    return false;
  return !/^ {0,3}([>|]|[-*+][ \t]|\d{1,9}[.)][ \t]|<!--)/.test(line);
}
function buildOverviewSection(summary, conceptNames) {
  const trimmed = (summary || "").trim();
  if (trimmed.length === 0)
    return "";
  const body = linkConceptNames(demoteHeadings(trimmed), conceptNames);
  return [
    "## \u{1F4CB} \uC804\uCCB4 \uC694\uC57D",
    "",
    OVERVIEW_BLOCK_START,
    body,
    OVERVIEW_BLOCK_END,
    "",
    ""
  ].join("\n");
}

// scripts/src/cli-common.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/overview-block.ts
async function main() {
  const [summaryFile, namesFile] = process.argv.slice(2);
  if (!summaryFile) {
    process.stderr.write("Usage: node scripts/phase2/overview-block.mjs <summaryFile> [conceptNamesJsonFile]\n");
    process.exit(2);
  }
  const summary = await readFile(summaryFile, "utf8");
  const names = namesFile ? JSON.parse(await readFile(namesFile, "utf8")) : [];
  if (!Array.isArray(names) || !names.every((n) => typeof n === "string")) {
    throw new Error("concept names file must be a JSON array of strings");
  }
  process.stdout.write(buildOverviewSection(summary, names));
}
main().catch((e) => fail(e, "overview-block"));
