// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/overview-block.ts
import { readFile } from "node:fs/promises";

// src/types.ts
var DEFAULT_GENERATION = {
  batchSize: 8,
  imageRule: "auto",
  transcriptCapChars: 600,
  tokenCapPerLecture: 0,
  saveKeyDiagrams: true,
  onlyChangedSlides: true
};
var TASK_DEFAULTS = {
  "claude-cli": {
    commentary: { model: "sonnet", effort: "medium" },
    concepts: { model: "haiku", effort: "low" },
    alignment: { model: "haiku", effort: "low" },
    verification: { model: "sonnet", effort: "medium" }
  },
  "codex-cli": {
    commentary: { model: "", effort: "medium" },
    concepts: { model: "", effort: "low" },
    alignment: { model: "", effort: "low" },
    verification: { model: "", effort: "medium" }
  }
};
var CLAUDE_TASK_DEFAULTS = {
  commentary: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].commentary },
  concepts: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].concepts },
  alignment: { provider: "none", model: "", effort: "" },
  verification: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].verification }
};
var DEFAULT_SETTINGS = {
  baseFolderPath: "Alt2Obsidian",
  language: "ko",
  settingsVersion: 3,
  claudePath: "",
  codexPath: "",
  cliTimeoutSec: 300,
  tasks: CLAUDE_TASK_DEFAULTS,
  preset: "custom",
  recentModels: {},
  generation: DEFAULT_GENERATION,
  altDataDir: "",
  notionFetchTool: "",
  hideManagedComments: true,
  openPdfInViewer: true
};
var EMPTY_USAGE = {
  calls: 0,
  inputTokens: 0,
  cachedInputTokens: 0,
  outputTokens: 0,
  imagesSent: 0,
  costUsd: 0
};
var DEFAULT_PLUGIN_DATA = {
  settings: DEFAULT_SETTINGS,
  recentImports: [],
  cliDetection: {},
  usageTotals: { ...EMPTY_USAGE, lectures: 0, byProvider: {}, since: "" }
};
var OVERVIEW_BLOCK_START = "<!-- alt2obs:overview start -->";
var OVERVIEW_BLOCK_END = "<!-- alt2obs:overview end -->";

// src/core/conceptNames.ts
var HANGUL = /[가-힣ㄱ-ㆎ]/;
function parseConceptName(name) {
  const full = name.trim();
  const m = full.match(/^(.+?)\s*\(([^()]+)\)$/);
  if (m) {
    const [a, b] = [m[1].trim(), m[2].trim()];
    const aKo = HANGUL.test(a);
    const bKo = HANGUL.test(b);
    if (aKo !== bKo)
      return { full, english: aKo ? b : a, korean: aKo ? a : b };
  }
  return HANGUL.test(full) ? { full, english: null, korean: full } : { full, english: full, korean: null };
}
function conceptKey(text) {
  return text.normalize("NFC").toLowerCase().replace(/[<>:"/\\|?*\x00-\x1f]/g, "").replace(/[\s_-]+/g, "");
}
function sameConcept(a, b) {
  if (conceptKey(a) === conceptKey(b))
    return true;
  const pa = parseConceptName(a);
  const pb = parseConceptName(b);
  const ea = pa.english ? conceptKey(pa.english) : "";
  const eb = pb.english ? conceptKey(pb.english) : "";
  if (ea && eb && ea === eb)
    return true;
  if (!pa.korean || !pb.korean || conceptKey(pa.korean) !== conceptKey(pb.korean))
    return false;
  return !ea || !eb || ea.startsWith(eb) || eb.startsWith(ea);
}

// src/core/markdown.ts
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
var ASCII_WORD = /[A-Za-z0-9]/;
var HANGUL_SYLLABLE = /[\uAC00-\uD7A3]/;
var PROTECTED = new RegExp(
  "(" + [
    "```[\\s\\S]*?(?:```|$)",
    "~~~[\\s\\S]*?(?:~~~|$)",
    "``[^\\n]*?``",
    "`[^`\\n]+`",
    "\\[\\[[^\\]\\n]*\\]\\]",
    "!?\\[[^\\]\\n]*\\]\\([^)\\n]*\\)",
    "https?:\\/\\/[^\\s)\\]]+",
    "\\$\\$[\\s\\S]*?\\$\\$",
    "\\$[^$\\n]+\\$",
    "<[^<>\\n]+>",
    "\\[\\^[^\\]\\n]*\\]"
  ].join("|") + ")"
);
function linkConceptNames(text, conceptNames) {
  const names = Array.from(new Set(conceptNames.map((n) => n.trim()).filter((n) => n.length > 0)));
  if (names.length === 0)
    return text;
  const terms = /* @__PURE__ */ new Map();
  for (const name of names) {
    const p = parseConceptName(name);
    const add = (term, whole) => {
      const key = term.toLowerCase();
      if (!term || terms.has(key) && !(whole && !terms.get(key).whole))
        return;
      terms.set(key, { term, concept: name, whole });
    };
    add(name, true);
    if (p.english && p.korean) {
      add(p.english, false);
      add(p.korean, false);
    }
  }
  const sorted = Array.from(terms.values()).sort((a, b) => b.term.length - a.term.length);
  const pattern = new RegExp(
    sorted.map(({ term }) => {
      const head = ASCII_WORD.test(term[0]) ? "(?<![A-Za-z0-9])" : HANGUL_SYLLABLE.test(term[0]) ? "(?<![\\uAC00-\\uD7A3])" : "";
      const tail = ASCII_WORD.test(term[term.length - 1]) ? "(?![A-Za-z0-9])" : "";
      return head + escapeRegex(term) + tail;
    }).join("|"),
    "gi"
  );
  const parts = text.split(PROTECTED);
  const linked = /* @__PURE__ */ new Set();
  for (let i = 1; i < parts.length; i += 2) {
    const m = parts[i].match(/^\[\[([^\]|#\n]+?)(?:#[^\]|]*)?(?:\\?\|[^\]]*)?\]\]$/);
    if (!m)
      continue;
    const target = m[1].trim();
    for (const name of names)
      if (sameConcept(target, name))
        linked.add(name);
  }
  const inTableRow = (at) => /^[ \t>]*\|/.test(text.slice(text.lastIndexOf("\n", at - 1) + 1));
  let base = 0;
  return parts.map((part, i) => {
    const start = base;
    base += part.length;
    if (i % 2 === 1)
      return part;
    return part.replace(pattern, (match, offset) => {
      const t = terms.get(match.toLowerCase());
      if (!t || linked.has(t.concept))
        return match;
      if (!t.whole && ASCII_WORD.test(match[match.length - 1]) && /^[ \t]+[A-Z][A-Za-z]/.test(part.slice(offset + match.length)))
        return match;
      if (!t.whole && ASCII_WORD.test(match[0]) && /[A-Z][A-Za-z]*[ \t]+$/.test(part.slice(0, offset)))
        return match;
      linked.add(t.concept);
      if (conceptKey(match) === conceptKey(t.concept))
        return `[[${t.concept}]]`;
      return `[[${t.concept}${inTableRow(start + offset) ? "\\|" : "|"}${match}]]`;
    });
  }).join("");
}
function demoteHeadings(markdown) {
  const out = [];
  let fence = null;
  let paragraphLines = 0;
  for (const line of markdown.split("\n")) {
    const fenceMatch = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (fence) {
      if (fenceMatch && fenceMatch[1][0] === fence.char && fenceMatch[1].length >= fence.len && fenceMatch[2].trim() === "") {
        fence = null;
      }
      out.push(line);
      continue;
    }
    if (fenceMatch && !(fenceMatch[1][0] === "`" && fenceMatch[2].includes("`"))) {
      fence = { char: fenceMatch[1][0], len: fenceMatch[1].length };
      out.push(line);
      paragraphLines = 0;
      continue;
    }
    const setext = line.match(/^ {0,3}(=+|-+)[ \t]*$/);
    if (setext && paragraphLines > 0) {
      const text = out.splice(out.length - paragraphLines, paragraphLines).map((l) => l.trim()).join(" ");
      out.push(`${setext[1][0] === "=" ? "##" : "###"} ${text}`);
      paragraphLines = 0;
      continue;
    }
    const atx = line.match(/^( {0,3})(#{1,6})(?=[ \t]|$)/);
    if (atx) {
      out.push(atx[2].length < 6 ? `${atx[1]}#${line.slice(atx[1].length)}` : line);
      paragraphLines = 0;
      continue;
    }
    out.push(line);
    paragraphLines = isParagraphLine(line) ? paragraphLines + 1 : 0;
  }
  return out.join("\n");
}
function isParagraphLine(line) {
  if (line.trim() === "")
    return false;
  if (/^ {4,}/.test(line))
    return false;
  return !/^ {0,3}([>|]|[-*+][ \t]|\d{1,9}[.)][ \t]|<!--)/.test(line);
}
function buildOverviewSection(summary, conceptNames) {
  const trimmed = (summary || "").trim();
  if (trimmed.length === 0)
    return "";
  const body = linkConceptNames(demoteHeadings(trimmed), conceptNames);
  return [
    "## \u{1F4CB} \uC804\uCCB4 \uC694\uC57D",
    "",
    OVERVIEW_BLOCK_START,
    body,
    OVERVIEW_BLOCK_END,
    "",
    ""
  ].join("\n");
}

// scripts/src/cli-common.ts
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/overview-block.ts
async function main() {
  const [summaryFile, namesFile] = process.argv.slice(2);
  if (!summaryFile) {
    process.stderr.write("Usage: node scripts/phase2/overview-block.mjs <summaryFile> [conceptNamesJsonFile]\n");
    process.exit(2);
  }
  const summary = await readFile(summaryFile, "utf8");
  const names = namesFile ? JSON.parse(await readFile(namesFile, "utf8")) : [];
  if (!Array.isArray(names) || !names.every((n) => typeof n === "string")) {
    throw new Error("concept names file must be a JSON array of strings");
  }
  process.stdout.write(buildOverviewSection(summary, names));
}
main().catch((e) => fail(e, "overview-block"));
