// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// scripts/src/prep.ts
import { spawnSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join as join2 } from "node:path";

// src/core/slideHash.ts
function normalizePageText(text) {
  return text.normalize("NFC").toLowerCase().replace(/\s+/g, "");
}
async function sha1Hex(input) {
  const digest = await crypto.subtle.digest("SHA-1", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function computeSlideHash(pageText, page, sourceId) {
  const normalized = pageText === null ? "" : normalizePageText(pageText);
  const key = normalized.length > 0 ? normalized : `${sourceId}:${page}`;
  return (await sha1Hex(key)).slice(0, 8);
}

// src/core/prep/SlideAnalyzer.ts
var DUPLICATE_SIMILARITY = 0.9;
var SCANNED_SHARE = 0.8;
var VISUAL_RATIO = 0.3;
var LOW_TEXT_CHARS = 30;
var LOW_TEXT_VISUAL_RATIO = 0.08;
var TOC_LINE = /^(table of contents|contents|목차|차례|outline|agenda)\s*:?$/i;
var THANKS_LINE = /^(thank you( very much)?|thanks|감사합니다|수고하셨습니다|q\s*&\s*a|questions?|any questions|질문 있나요|the end|끝)\s*[!.?]*$/i;
var COVER_TITLE = /\b(lecture|lec\.?|chapter|week|unit|session)\s*\d+|\b[A-Z]{2,6}\s?-?\d{3,4}[A-Z]?\b|제\s*\d+\s*강|\d+\s*강\b|\d+\s*주차|강의/i;
var COVER_AFFILIATION = /universit|department|dept\.|school of|college|institute|laborator|\blab\b|professor|prof\.|@[\w.-]+\.[a-z]{2,}|대학|학과|학부|연구실|교수/i;
var COVER_MAX_CHARS = 1200;
function bigrams(s) {
  const m = /* @__PURE__ */ new Map();
  for (let i = 0; i < s.length - 1; i++) {
    const g = s.slice(i, i + 2);
    m.set(g, (m.get(g) ?? 0) + 1);
  }
  return m;
}
function textSimilarity(a, b) {
  const na = normalizePageText(a);
  const nb = normalizePageText(b);
  if (na === nb)
    return na.length > 0 ? 1 : 0;
  if (na.length < 2 || nb.length < 2)
    return 0;
  const ga = bigrams(na);
  const gb = bigrams(nb);
  let common = 0;
  for (const [g, c] of ga)
    common += Math.min(c, gb.get(g) ?? 0);
  return 2 * common / (na.length - 1 + nb.length - 1);
}
function slideTitle(text) {
  const t = (text ?? "").replace(/\s+/g, " ").trim();
  if (!t)
    return "";
  return t.length > 40 ? `${t.slice(0, 40)}...` : t;
}
function backgroundLevel(gray) {
  const hist = new Array(32).fill(0);
  for (let i = 0; i < gray.data.length; i++)
    hist[gray.data[i] >> 3]++;
  let best = 0;
  for (let b = 1; b < 32; b++)
    if (hist[b] > hist[best])
      best = b;
  return best * 8 + 4;
}
function computeImageRatio(gray, boxes, grid = 16) {
  if (gray.width === 0 || gray.height === 0)
    return 0;
  const bg = backgroundLevel(gray);
  let graphic = 0;
  for (let gy = 0; gy < grid; gy++) {
    for (let gx = 0; gx < grid; gx++) {
      const x0 = Math.floor(gx * gray.width / grid);
      const x1 = Math.max(x0 + 1, Math.floor((gx + 1) * gray.width / grid));
      const y0 = Math.floor(gy * gray.height / grid);
      const y1 = Math.max(y0 + 1, Math.floor((gy + 1) * gray.height / grid));
      let ink = 0;
      for (let y = y0; y < y1; y++) {
        for (let x = x0; x < x1; x++) {
          if (Math.abs(gray.data[y * gray.width + x] - bg) > 40)
            ink++;
        }
      }
      if (ink / ((x1 - x0) * (y1 - y0)) < 0.03)
        continue;
      const cx0 = gx / grid;
      const cy0 = gy / grid;
      const cell = 1 / grid;
      let covered = 0;
      for (const b of boxes) {
        const ox = Math.max(0, Math.min(cx0 + cell, b.x + b.w) - Math.max(cx0, b.x));
        const oy = Math.max(0, Math.min(cy0 + cell, b.y + b.h) - Math.max(cy0, b.y));
        covered += ox * oy;
      }
      if (covered / (cell * cell) < 0.3)
        graphic++;
    }
  }
  return Math.round(graphic / (grid * grid) * 1e3) / 1e3;
}
function averageHash(gray, size = 16) {
  const cells = [];
  for (let gy = 0; gy < size; gy++) {
    for (let gx = 0; gx < size; gx++) {
      const x0 = Math.floor(gx * gray.width / size);
      const x1 = Math.max(x0 + 1, Math.floor((gx + 1) * gray.width / size));
      const y0 = Math.floor(gy * gray.height / size);
      const y1 = Math.max(y0 + 1, Math.floor((gy + 1) * gray.height / size));
      let sum = 0;
      let n = 0;
      for (let y = y0; y < y1 && y < gray.height; y++) {
        for (let x = x0; x < x1 && x < gray.width; x++) {
          sum += gray.data[y * gray.width + x];
          n++;
        }
      }
      cells.push(n > 0 ? sum / n : 0);
    }
  }
  const mean = cells.reduce((a, b) => a + b, 0) / cells.length;
  let hex = "";
  for (let i = 0; i < cells.length; i += 4) {
    let nibble = 0;
    for (let k = 0; k < 4; k++)
      nibble = nibble << 1 | (cells[i + k] > mean ? 1 : 0);
    hex += nibble.toString(16);
  }
  return hex;
}
function luminanceGrid(gray, size = 8) {
  let hex = "";
  for (let gy = 0; gy < size; gy++) {
    for (let gx = 0; gx < size; gx++) {
      const x0 = Math.floor(gx * gray.width / size);
      const x1 = Math.max(x0 + 1, Math.floor((gx + 1) * gray.width / size));
      const y0 = Math.floor(gy * gray.height / size);
      const y1 = Math.max(y0 + 1, Math.floor((gy + 1) * gray.height / size));
      let sum = 0;
      let cnt = 0;
      for (let y = y0; y < y1 && y < gray.height; y++) {
        for (let x = x0; x < x1 && x < gray.width; x++) {
          sum += gray.data[y * gray.width + x];
          cnt++;
        }
      }
      hex += Math.min(15, Math.floor((cnt > 0 ? sum / cnt : 0) / 16)).toString(16);
    }
  }
  return hex;
}
function imageSignal(gray) {
  return averageHash(gray) + luminanceGrid(gray);
}
function signalDistance(a, b) {
  if (!a || !b || a.length !== b.length)
    return Infinity;
  let d = 0;
  for (let i = 0; i < a.length; i++) {
    let x = parseInt(a[i], 16) ^ parseInt(b[i], 16);
    while (x) {
      d += x & 1;
      x >>= 1;
    }
  }
  return d;
}
function sameImageSignal(a, b) {
  if (!a || !b || a.length !== 128 || b.length !== 128)
    return false;
  if (signalDistance(a.slice(0, 64), b.slice(0, 64)) > 2)
    return false;
  let cells = 0;
  for (let i = 64; i < 128; i++) {
    const d = Math.abs(parseInt(a[i], 16) - parseInt(b[i], 16));
    if (d > 1)
      return false;
    if (d === 1)
      cells++;
  }
  return cells <= 2;
}
function contentLines(text, lines) {
  return (lines ?? [text ?? ""]).map((l) => l.replace(/\s+/g, " ").trim()).filter((l) => l.length > 0 && !/^\d{1,3}$/.test(l));
}
function looksLikeCover(text, lines) {
  const chars = normalizePageText(text ?? "").length;
  if (chars <= 150)
    return true;
  if (chars > COVER_MAX_CHARS)
    return false;
  const ls = contentLines(text, lines);
  if (ls.some((l) => /^[•◼▪■●◦\-*]\s/.test(l)))
    return false;
  return ls.slice(0, 3).some((l) => COVER_TITLE.test(l)) && ls.some((l) => COVER_AFFILIATION.test(l));
}
function classifySlide(index, pageCount, text, imageRatio, lines) {
  const norm = normalizePageText(text ?? "");
  const chars = norm.length;
  const ls = contentLines(text, lines);
  if (index === 0 && looksLikeCover(text, lines))
    return "cover";
  if (index >= pageCount - 2 && chars > 0 && chars <= 120 && ls.length > 0 && THANKS_LINE.test(ls[0])) {
    const rest = ls.slice(1).join(" ");
    if (rest.length <= 40 && !/^[•◼▪■●◦\-*]/m.test(ls.slice(1).join("\n")))
      return "thanks";
  }
  const tocWindow = Math.max(3, Math.ceil(pageCount * 0.15));
  if (index < tocWindow && chars > 0 && chars <= 500 && ls.length > 0 && TOC_LINE.test(ls[0]))
    return "toc";
  if (imageRatio === null)
    return chars < LOW_TEXT_CHARS ? "visual" : "content";
  if (chars < LOW_TEXT_CHARS && imageRatio >= LOW_TEXT_VISUAL_RATIO)
    return "visual";
  if (imageRatio >= VISUAL_RATIO)
    return "visual";
  if (chars === 0)
    return "visual";
  return "content";
}
function tokens(text) {
  return text.normalize("NFC").toLowerCase().match(/[a-z]+|\d+(?:\.\d+)?|[\uac00-\ud7a3]+|[^\s\w]/g) ?? [];
}
function isBuildStep(a, b) {
  if (textSimilarity(a, b) < DUPLICATE_SIMILARITY)
    return false;
  const ta = tokens(a);
  const pool = /* @__PURE__ */ new Map();
  for (const t of tokens(b))
    pool.set(t, (pool.get(t) ?? 0) + 1);
  if (tokens(b).length < ta.length)
    return false;
  let missingWords = 0;
  for (const t of ta) {
    const n = pool.get(t) ?? 0;
    if (n > 0) {
      pool.set(t, n - 1);
      continue;
    }
    if (/^\d/.test(t))
      return false;
    missingWords++;
  }
  return missingWords <= Math.floor(ta.length * 0.03);
}
async function analyzeSlides(layouts, grays, opts) {
  const n = layouts.length;
  const textless = layouts.filter((l) => normalizePageText(l.text ?? "").length === 0).length;
  const scanned = n > 0 && textless / n >= SCANNED_SHARE;
  const slides = [];
  for (let i = 0; i < n; i++) {
    const layout = layouts[i];
    const gray = grays[i] ?? null;
    const imageRatio = gray ? computeImageRatio(gray, layout.boxes) : null;
    const kind = scanned ? "content" : classifySlide(i, n, layout.text, imageRatio, layout.lines);
    slides.push({
      page: i + 1,
      hash: await computeSlideHash(layout.text, i + 1, opts.sourceId),
      textChars: normalizePageText(layout.text ?? "").length,
      imageRatio,
      kind,
      dupOf: null,
      sendImage: scanned || kind === "visual" && opts.imageRule !== "text-only",
      title: slideTitle(layout.text),
      imageSignal: gray ? imageSignal(gray) : null
    });
  }
  const generated = (s) => s.kind === "content" || s.kind === "visual";
  for (let i = n - 2; i >= 0; i--) {
    const a = slides[i];
    const b = slides[i + 1];
    if (!generated(a) || !generated(b) || a.textChars < 20 || b.textChars < 20)
      continue;
    if ((a.kind === "visual" || b.kind === "visual") && !sameImageSignal(a.imageSignal, b.imageSignal))
      continue;
    if (isBuildStep(layouts[i].text ?? "", layouts[i + 1].text ?? "")) {
      a.dupOf = b.dupOf ?? b.page;
    }
  }
  return { slides, scanned };
}
var MAX_KEY_DIAGRAMS = 8;
function selectKeyDiagrams(slides, scanned, max = MAX_KEY_DIAGRAMS) {
  if (scanned)
    return [];
  return slides.filter((s) => s.kind === "visual" && s.dupOf === null && s.imageRatio !== null && s.imageRatio >= VISUAL_RATIO).sort((a, b) => (b.imageRatio ?? 0) - (a.imageRatio ?? 0) || a.page - b.page).slice(0, max).map((s) => s.page).sort((a, b) => a - b);
}
function templateCommentary(slide, deckTitle) {
  if (slide.dupOf !== null) {
    return `\uB2E4\uC74C \uC2AC\uB77C\uC774\uB4DC\uC640 \uAC19\uC740 \uB0B4\uC6A9\uC774\uB2E4. \uD574\uC124\uC740 [[#\u{1F4DA} \uC2AC\uB77C\uC774\uB4DC ${slide.dupOf}|\uC2AC\uB77C\uC774\uB4DC ${slide.dupOf}]]\uC5D0 \uC788\uB2E4.`;
  }
  switch (slide.kind) {
    case "cover":
      return `\uD45C\uC9C0 \uC2AC\uB77C\uC774\uB4DC: **${slide.title || deckTitle}**`;
    case "toc":
      return "\uBAA9\uCC28 \uC2AC\uB77C\uC774\uB4DC\uB2E4. \uC774\uBC88 \uAC15\uC758\uC5D0\uC11C \uB2E4\uB8F0 \uD56D\uBAA9\uC744 \uB298\uC5B4\uB193\uB294\uB2E4.";
    case "thanks":
      return "\uB9C8\uBB34\uB9AC \uC2AC\uB77C\uC774\uB4DC\uB2E4.";
    default:
      return null;
  }
}

// src/core/prep/pageLayout.ts
function itemBox(item, view) {
  const t = item.transform;
  if (!t || !item.str || !item.str.trim())
    return null;
  const [x0, y0, x1, y1] = view;
  const pw = x1 - x0;
  const ph = y1 - y0;
  if (pw <= 0 || ph <= 0)
    return null;
  const h = Math.abs(item.height || t[3] || 0);
  const w = Math.abs(item.width || 0);
  const left = (t[4] - x0) / pw;
  const top = 1 - (t[5] + h - y0) / ph;
  return { x: left, y: top, w: w / pw, h: h / ph };
}
async function extractPageLayouts(pdf) {
  const out = [];
  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    try {
      const page = await pdf.getPage(pageNum);
      const content = await page.getTextContent();
      const items = content.items;
      const view = page.view ?? [0, 0, 1, 1];
      const lines = [];
      let line = "";
      for (const item of items) {
        line += item.str ?? "";
        if (item.hasEOL) {
          lines.push(line);
          line = "";
        }
      }
      if (line)
        lines.push(line);
      out.push({
        text: items.map((item) => item.str ?? "").join(""),
        boxes: items.map((item) => itemBox(item, view)).filter((b) => b !== null),
        lines
      });
    } catch (e) {
      console.warn(`[Alt2Obs] layout extraction failed for page ${pageNum}:`, e);
      out.push({ text: null, boxes: [], lines: [] });
    }
  }
  return out;
}
function parsePgm(bytes) {
  let pos = 0;
  const token = () => {
    for (; ; ) {
      while (pos < bytes.length && /\s/.test(String.fromCharCode(bytes[pos])))
        pos++;
      if (bytes[pos] === 35) {
        while (pos < bytes.length && bytes[pos] !== 10)
          pos++;
        continue;
      }
      break;
    }
    let s = "";
    while (pos < bytes.length && !/\s/.test(String.fromCharCode(bytes[pos])))
      s += String.fromCharCode(bytes[pos++]);
    return s;
  };
  if (token() !== "P5")
    throw new Error("not a binary PGM (P5) image");
  const width = parseInt(token(), 10);
  const height = parseInt(token(), 10);
  const maxval = parseInt(token(), 10);
  if (!(width > 0 && height > 0) || !(maxval > 0 && maxval < 256))
    throw new Error("unsupported PGM header");
  pos++;
  const data = bytes.subarray(pos, pos + width * height);
  if (data.length < width * height)
    throw new Error("truncated PGM data");
  if (maxval === 255)
    return { width, height, data };
  const scaled = new Uint8Array(width * height);
  for (let i = 0; i < scaled.length; i++)
    scaled[i] = Math.round(data[i] * 255 / maxval);
  return { width, height, data: scaled };
}
var ANALYSIS_LONG_EDGE = 160;
function layoutAlignmentText(layout) {
  return layout.lines && layout.lines.length > 0 ? layout.lines.join("\n") : layout.text ?? "";
}

// src/core/prep/TranscriptAligner.ts
var LOW_CONFIDENCE = 0.45;
var DEFAULT_ALIGNER_PARAMS = {
  windowMs: 15e3,
  damping: 0.4,
  nextCost: 1.2,
  skipCost: 1.5,
  backCost: 6,
  backPerSlide: 0.05,
  offEmission: 0.5,
  offCost: 1,
  titleWeight: 1,
  bm25K1: 1.2,
  bm25B: 0.75
};
var EN_STOPWORDS = new Set(
  "a an the and or but if then than so as at by for from in into of on onto to with without within about above below over under is are was were be been being am do does did done doing have has had having can could will would shall should may might must this that these those there here it its it's they them their we us our you your he she his her i me my mine what which who whom whose when where why how all any both each few more most other some such no nor not only own same very just also too again further once now okay ok yeah yes right well like really actually basically kind sort thing things let lets go going get got say said see look talk think know want need make made use used using one two way ll ve re don doesn didn isn aren wasn slide slides lecture today class question questions answer example examples".split(/\s+/)
);
var KO_STOPWORDS = new Set(
  "\uADF8\uB9AC\uACE0 \uADF8\uB798\uC11C \uADF8\uB7EC\uBA74 \uADF8\uB7EC\uB2C8\uAE4C \uADF8\uB7F0\uB370 \uD558\uC9C0\uB9CC \uADF8\uB7EC\uB098 \uB610\uB294 \uD639\uC740 \uC774\uC81C \uC9C0\uAE08 \uC5EC\uAE30 \uAC70\uAE30 \uC800\uAE30 \uC774\uAC83 \uADF8\uAC83 \uC800\uAC83 \uC774\uAC70 \uADF8\uAC70 \uC800\uAC70 \uC774\uB7F0 \uADF8\uB7F0 \uC800\uB7F0 \uC774\uB807\uAC8C \uADF8\uB807\uAC8C \uC800\uB807\uAC8C \uC6B0\uB9AC \uC5EC\uB7EC\uBD84 \uC81C\uAC00 \uC800\uB294 \uB098\uB294 \uB0B4\uAC00 \uB108\uBB34 \uC815\uB9D0 \uC9C4\uC9DC \uC57D\uAC04 \uC870\uAE08 \uB9CE\uC774 \uADF8\uB0E5 \uC77C\uB2E8 \uB2E4\uC2DC \uACC4\uC18D \uBA3C\uC800 \uB2E4\uC74C \uC788\uC2B5\uB2C8\uB2E4 \uC788\uC5B4\uC694 \uC788\uB294 \uC788\uACE0 \uC5C6\uC2B5\uB2C8\uB2E4 \uC5C6\uB294 \uD569\uB2C8\uB2E4 \uD574\uC694 \uD558\uB294 \uD558\uACE0 \uD574\uC11C \uD588\uC2B5\uB2C8\uB2E4 \uB429\uB2C8\uB2E4 \uB418\uB294 \uB41C\uB2E4 \uC774\uB2E4 \uC785\uB2C8\uB2E4 \uC5D0\uC694 \uC608\uC694 \uAC83\uC774 \uAC83\uC740 \uAC83\uC744 \uAC70\uC8E0 \uAC70\uC608\uC694 \uAC70\uC5D0\uC694 \uBB50\uB0D0 \uBB34\uC5C7 \uC5B4\uB5A4 \uC5B4\uB5BB\uAC8C \uC65C\uB0D0 \uB54C\uBB38 \uACBD\uC6B0 \uBD80\uBD84 \uC815\uB3C4 \uC2AC\uB77C\uC774\uB4DC \uAC15\uC758 \uC624\uB298 \uC9C8\uBB38".split(/\s+/)
);
var KO_SUFFIXES = [
  "\uC5D0\uC11C\uB294",
  "\uC73C\uB85C\uB294",
  "\uC774\uB77C\uB294",
  "\uC774\uB77C\uACE0",
  "\uC785\uB2C8\uB2E4",
  "\uD588\uC2B5\uB2C8\uB2E4",
  "\uD569\uB2C8\uB2E4",
  "\uC5D0\uAC8C\uC11C",
  "\uAE4C\uC9C0\uB294",
  "\uBD80\uD130\uB294",
  "\uC5D0\uC11C",
  "\uC73C\uB85C",
  "\uC5D0\uAC8C",
  "\uAE4C\uC9C0",
  "\uBD80\uD130",
  "\uB77C\uB294",
  "\uB77C\uACE0",
  "\uC774\uACE0",
  "\uC774\uBA70",
  "\uD558\uB294",
  "\uD558\uACE0",
  "\uD574\uC11C",
  "\uD588\uB2E4",
  "\uD55C\uB2E4",
  "\uB41C\uB2E4",
  "\uB418\uB294",
  "\uCC98\uB7FC",
  "\uBCF4\uB2E4",
  "\uB9C8\uB2E4",
  "\uC774\uB098",
  "\uC5D0\uB294",
  "\uC640\uB294",
  "\uACFC\uB294",
  "\uB4E4\uC774",
  "\uB4E4\uC744",
  "\uB4E4\uC740",
  "\uB4E4\uC758",
  "\uC740",
  "\uB294",
  "\uC774",
  "\uAC00",
  "\uC744",
  "\uB97C",
  "\uC5D0",
  "\uC758",
  "\uB85C",
  "\uC640",
  "\uACFC",
  "\uB3C4",
  "\uB9CC",
  "\uB4E4",
  "\uACE0",
  "\uB2E4",
  "\uC694"
].sort((a, b) => b.length - a.length);
function stemEnglish(w) {
  let t = w;
  if (t.length > 4 && t.endsWith("ies"))
    t = t.slice(0, -3) + "y";
  else if (t.length > 4 && t.endsWith("sses"))
    t = t.slice(0, -2);
  else if (t.length > 3 && t.endsWith("s") && !t.endsWith("ss"))
    t = t.slice(0, -1);
  if (t.length > 5 && t.endsWith("ing"))
    t = t.slice(0, -3);
  else if (t.length > 4 && t.endsWith("ed"))
    t = t.slice(0, -2);
  return t;
}
function stemKorean(w) {
  for (const s of KO_SUFFIXES) {
    if (w.length - s.length >= 2 && w.endsWith(s))
      return w.slice(0, -s.length);
  }
  return w;
}
function alignTokens(text) {
  const out = [];
  const lower = text.normalize("NFKC").toLowerCase();
  for (const m of lower.matchAll(/[a-z][a-z0-9]*|\d+(?:\.\d+)?|[가-힣]+/g)) {
    const w = m[0];
    if (/^[가-힣]/.test(w)) {
      if (w.length < 2 || KO_STOPWORDS.has(w))
        continue;
      const stem = stemKorean(w);
      if (stem.length < 2 || KO_STOPWORDS.has(stem))
        continue;
      out.push(stem);
    } else if (/^\d/.test(w)) {
      if (w.length >= 2)
        out.push(w);
    } else {
      if (w.length < 2 || EN_STOPWORDS.has(w))
        continue;
      const stem = stemEnglish(w);
      if (stem.length < 2 || EN_STOPWORDS.has(stem))
        continue;
      out.push(stem);
    }
  }
  return out;
}
function indexSlides(slideTexts, titleWeight) {
  const tf = slideTexts.map((t) => {
    const m = /* @__PURE__ */ new Map();
    const title = t.split("\n").find((line) => line.trim().length > 0) ?? "";
    const titleTokens = alignTokens(title);
    for (const tok of alignTokens(t))
      m.set(tok, (m.get(tok) ?? 0) + 1);
    for (let r = 0; r < titleWeight; r++)
      for (const tok of titleTokens)
        m.set(tok, (m.get(tok) ?? 0) + 1);
    return m;
  });
  const len = tf.map((m) => Array.from(m.values()).reduce((a, b) => a + b, 0));
  const avgLen = Math.max(1, len.reduce((a, b) => a + b, 0) / Math.max(1, len.length));
  const df = /* @__PURE__ */ new Map();
  for (const m of tf)
    for (const t of m.keys())
      df.set(t, (df.get(t) ?? 0) + 1);
  const n = slideTexts.length;
  const idf = /* @__PURE__ */ new Map();
  for (const [t, d] of df)
    idf.set(t, Math.log(1 + (n - d + 0.5) / (d + 0.5)));
  return { tf, len, avgLen, idf };
}
function bm25(query, index, p) {
  const scores = new Array(index.tf.length).fill(0);
  for (const [term] of query) {
    const idf = index.idf.get(term);
    if (idf === void 0)
      continue;
    for (let j = 0; j < index.tf.length; j++) {
      const f = index.tf[j].get(term);
      if (!f)
        continue;
      const norm = p.bm25K1 * (1 - p.bm25B + p.bm25B * index.len[j] / index.avgLen);
      scores[j] += idf * f * (p.bm25K1 + 1) / (f + norm);
    }
  }
  return scores;
}
function emissionScores(slideTexts, segments, p = DEFAULT_ALIGNER_PARAMS) {
  const index = indexSlides(slideTexts, p.titleWeight);
  const segTokens = segments.map((s) => alignTokens(s.text));
  const raw = [];
  const bests = [];
  let lo = 0;
  let hi = 0;
  for (let i = 0; i < segments.length; i++) {
    const from = segments[i].startMs - p.windowMs;
    const to = segments[i].endMs + p.windowMs;
    while (lo < segments.length && segments[lo].endMs < from)
      lo++;
    if (hi < i)
      hi = i;
    while (hi + 1 < segments.length && segments[hi + 1].startMs <= to)
      hi++;
    const query = /* @__PURE__ */ new Map();
    for (let k = Math.min(lo, i); k <= hi; k++)
      for (const t of segTokens[k])
        query.set(t, (query.get(t) ?? 0) + 1);
    const scores = bm25(query, index, p);
    raw.push(scores);
    bests.push(Math.max(0, ...scores));
  }
  const sorted = bests.filter((b) => b > 0).sort((a, b) => a - b);
  const typical = sorted.length > 0 ? sorted[Math.floor(sorted.length / 2)] : 1;
  const damp = p.damping * typical;
  return raw.map((scores, i) => scores.map((s) => s / (bests[i] + damp)));
}
var MIN_SLIDE_TOKENS = 3;
function textSlideMask(slideTexts) {
  return slideTexts.map((t) => alignTokens(t).length >= MIN_SLIDE_TOKENS);
}
function transitionCost(from, to, p, textBefore) {
  if (to === from)
    return 0;
  if (to === from + 1)
    return p.nextCost;
  if (to > from)
    return p.nextCost + p.skipCost * (textBefore[to] - textBefore[from + 1]);
  return p.backCost + p.backPerSlide * (from - to);
}
var MAX_MOVED_TALK_MS = 6e4;
function giveOffTalkToSkippedTextless(path, off, isText, segments, maxCount) {
  for (let i = 1; i < path.length; i++) {
    const from = path[i - 1];
    const to = path[i];
    if (to <= from + 1)
      continue;
    const between = [];
    for (let j = from + 1; j < to; j++)
      if (!isText[j])
        between.push(j);
    if (between.length === 0)
      continue;
    let k = i;
    while (k > 0 && off[k - 1] && path[k - 1] === from && i - (k - 1) <= maxCount && segments[i - 1].endMs - segments[k - 1].startMs <= MAX_MOVED_TALK_MS)
      k--;
    const len = i - k;
    for (let q = 0; q < len; q++)
      path[k + q] = between[Math.min(between.length - 1, Math.floor(q * between.length / len))];
  }
}
function spreadTextless(path, isText) {
  const n = path.length;
  let i = 0;
  while (i < n) {
    if (isText[path[i]]) {
      i++;
      continue;
    }
    let a = path[i];
    while (a > 0 && !isText[a - 1])
      a--;
    let b = path[i];
    while (b + 1 < isText.length && !isText[b + 1])
      b++;
    let k = i;
    while (k < n && path[k] >= a && path[k] <= b)
      k++;
    const len = k - i;
    const slides = b - a + 1;
    if (slides > 1)
      for (let q = 0; q < len; q++)
        path[i + q] = a + Math.min(slides - 1, Math.floor(q * slides / len));
    i = k;
  }
}
function alignTranscript(slideTexts, segments, params = {}) {
  const p = { ...DEFAULT_ALIGNER_PARAMS, ...params };
  const m = slideTexts.length;
  const n = segments.length;
  if (m === 0 || n === 0)
    return { spans: [], segmentSlides: [] };
  const e = emissionScores(slideTexts, segments, p);
  const isText = textSlideMask(slideTexts);
  const textBefore = new Int32Array(m + 1);
  for (let j = 0; j < m; j++)
    textBefore[j + 1] = textBefore[j] + (isText[j] ? 1 : 0);
  for (const row of e)
    for (let j = 0; j < m; j++)
      if (!isText[j])
        row[j] = p.offEmission;
  let on = new Float64Array(m);
  let off = new Float64Array(m);
  for (let j = 0; j < m; j++) {
    const enter = j === 0 ? 0 : (p.nextCost + p.skipCost * textBefore[j]) * 0.5;
    on[j] = e[0][j] - enter;
    off[j] = p.offEmission - p.offCost - enter;
  }
  const back = [new Int32Array(2 * m).fill(-1)];
  const best = new Float64Array(m);
  const bestState = new Int32Array(m);
  for (let i = 1; i < n; i++) {
    for (let j = 0; j < m; j++) {
      if (off[j] > on[j]) {
        best[j] = off[j];
        bestState[j] = m + j;
      } else {
        best[j] = on[j];
        bestState[j] = j;
      }
    }
    const nextOn = new Float64Array(m);
    const nextOff = new Float64Array(m);
    const ptr = new Int32Array(2 * m);
    for (let k = 0; k < m; k++) {
      let v = -Infinity;
      let arg = k;
      for (let j = 0; j < m; j++) {
        const c = best[j] - transitionCost(j, k, p, textBefore);
        if (c > v) {
          v = c;
          arg = bestState[j];
        }
      }
      nextOn[k] = v + e[i][k];
      ptr[k] = arg;
      const stay = off[k];
      const drift = on[k] - p.offCost;
      nextOff[k] = Math.max(stay, drift) + p.offEmission;
      ptr[m + k] = stay >= drift ? m + k : k;
    }
    back.push(ptr);
    on = nextOn;
    off = nextOff;
  }
  let lastState = 0;
  let lastScore = -Infinity;
  for (let j = 0; j < m; j++) {
    if (on[j] > lastScore) {
      lastScore = on[j];
      lastState = j;
    }
    if (off[j] > lastScore) {
      lastScore = off[j];
      lastState = m + j;
    }
  }
  const states = new Array(n);
  states[n - 1] = lastState;
  for (let i = n - 1; i > 0; i--)
    states[i - 1] = back[i][states[i]];
  const path = states.map((st) => st % m);
  const visited = new Set(path).size;
  const perSlide = Math.max(1, Math.round(n / Math.max(1, visited)));
  giveOffTalkToSkippedTextless(path, states.map((st) => st >= m), isText, segments, perSlide);
  spreadTextless(path, isText);
  const spans = [];
  let start = 0;
  for (let i = 1; i <= n; i++) {
    if (i < n && path[i] === path[start])
      continue;
    const j = path[start];
    let own = 0;
    let other = 0;
    for (let k = start; k < i; k++) {
      own += e[k][j];
      let alt = 0;
      for (let q = 0; q < m; q++)
        if (q !== j && e[k][q] > alt)
          alt = e[k][q];
      other += alt;
    }
    const share = own + other > 0 ? own / (own + other) : 0;
    const evidence = Math.min(1, own / 3);
    spans.push({
      slide: j + 1,
      startMs: segments[start].startMs,
      endMs: segments[i - 1].endMs,
      fromSegment: start,
      toSegment: i,
      confidence: Math.round(share * (0.5 + 0.5 * evidence) * 100) / 100
    });
    start = i;
  }
  return { spans, segmentSlides: path.map((j) => j + 1) };
}
function chunksFromAlignment(result, segments, slideCount) {
  const parts = Array.from({ length: slideCount }, () => []);
  result.segmentSlides.forEach((slide, i) => {
    if (slide >= 1 && slide <= slideCount)
      parts[slide - 1].push(segments[i].text.trim());
  });
  return parts.map((p) => {
    const text = p.filter((t) => t.length > 0).join(" ");
    return text.length > 0 ? text : null;
  });
}
function tenths(ms) {
  return (ms / 1e3).toFixed(1).replace(/\.0$/, "");
}
function toTenth(ms) {
  return Math.floor(ms / 100) * 100;
}
function formatAlignment(spans) {
  return spans.map((s, i) => {
    const start = toTenth(s.startMs);
    const end = i + 1 < spans.length ? toTenth(spans[i + 1].startMs) : Math.ceil(s.endMs / 100) * 100;
    return `${s.slide}:${tenths(start)}-${tenths(Math.max(start, end))}${s.confidence < LOW_CONFIDENCE ? "?" : ""}`;
  }).join(" ");
}

// src/pipeline/alignment.ts
function timedSegments(segments) {
  if (!segments || segments.length === 0)
    return null;
  const timedCount = segments.filter((s) => s.startMs !== null && s.endMs !== null).length;
  if (timedCount === 0 || timedCount < segments.length * 0.9)
    return null;
  const out = [];
  let last = 0;
  for (const s of segments) {
    const start = s.startMs ?? last;
    const end = s.endMs ?? start;
    out.push({ startMs: start, endMs: Math.max(end, start), text: s.text });
    last = Math.max(end, start);
  }
  return out.sort((a, b) => a.startMs - b.startMs);
}
function finish(result, segments, slideCount, llmChanged) {
  return {
    result,
    segments,
    chunks: chunksFromAlignment(result, segments, slideCount),
    value: formatAlignment(result.spans),
    lowSpans: result.spans.filter((s) => s.confidence < LOW_CONFIDENCE),
    llmChanged
  };
}
var MIN_TEXT_SLIDE_SHARE = 0.5;
function alignLecture(slideTexts, segments, opts = {}) {
  const timed = timedSegments(segments);
  if (!timed || slideTexts.length === 0 || opts.scanned)
    return null;
  const textSlides = textSlideMask(slideTexts).filter(Boolean).length;
  if (textSlides < slideTexts.length * MIN_TEXT_SLIDE_SHARE)
    return null;
  return finish(alignTranscript(slideTexts, timed), timed, slideTexts.length, 0);
}

// src/types.ts
var DEFAULT_GENERATION = {
  batchSize: 8,
  imageRule: "auto",
  transcriptCapChars: 1200,
  tokenCapPerLecture: 0,
  saveKeyDiagrams: true,
  onlyChangedSlides: true
};
var TASK_DEFAULTS = {
  "claude-cli": {
    commentary: { model: "sonnet", effort: "medium" },
    concepts: { model: "haiku", effort: "low" },
    alignment: { model: "haiku", effort: "low" },
    verification: { model: "sonnet", effort: "medium" }
  },
  "codex-cli": {
    commentary: { model: "", effort: "medium" },
    concepts: { model: "", effort: "low" },
    alignment: { model: "", effort: "low" },
    verification: { model: "", effort: "medium" }
  }
};
var CLAUDE_TASK_DEFAULTS = {
  commentary: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].commentary },
  concepts: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].concepts },
  alignment: { provider: "none", model: "", effort: "" },
  verification: { provider: "claude-cli", ...TASK_DEFAULTS["claude-cli"].verification }
};
var DEFAULT_SETTINGS = {
  // The folder name from before the rename to Alt2Obs (2.0.0): existing
  // vaults and the Skill keep writing to the same place.
  baseFolderPath: "Alt2Obsidian",
  language: "ko",
  settingsVersion: 3,
  claudePath: "",
  codexPath: "",
  cliTimeoutSec: 300,
  tasks: CLAUDE_TASK_DEFAULTS,
  preset: "custom",
  recentModels: {},
  generation: DEFAULT_GENERATION,
  altDataDir: "",
  notionFetchTool: "",
  hideManagedComments: true,
  openPdfInViewer: true
};
var EMPTY_USAGE = {
  calls: 0,
  inputTokens: 0,
  cachedInputTokens: 0,
  outputTokens: 0,
  imagesSent: 0,
  costUsd: 0
};
var DEFAULT_PLUGIN_DATA = {
  settings: DEFAULT_SETTINGS,
  recentImports: [],
  cliDetection: {},
  usageTotals: { ...EMPTY_USAGE, lectures: 0, byProvider: {}, since: "" }
};

// src/core/sections.ts
var SECTION_HEADING_PATTERN = "## \u23F1 \uAD6C\uAC04 (\\d+)";
var SECTION_MARKER_PATTERN = "<!-- alt2obs:section:(\\d+) hash:([0-9a-f]{8}) (start|end) -->";
var HEADING_RE = new RegExp(`^${SECTION_HEADING_PATTERN}(?: \\[([0-9:]+)~([0-9:]+)\\])?(.*)$`);

// src/core/merge.ts
function splitMultiManagedNote(content) {
  const fmMatch = content.match(/^---\n[\s\S]*?\n---\n*/);
  const frontmatter = fmMatch ? fmMatch[0] : "";
  const body = fmMatch ? content.slice(fmMatch[0].length) : content;
  const markers = [];
  const re = /<!-- alt2obs:slide:(\d+) hash:([0-9a-f]{8})(?: dup:(\d+))? (start|end) -->/g;
  let m;
  while ((m = re.exec(body)) !== null) {
    markers.push({
      idx: m.index,
      end: m.index + m[0].length,
      slideNum: parseInt(m[1], 10),
      hash: m[2],
      dup: m[3] ? parseInt(m[3], 10) : void 0,
      type: m[4]
    });
  }
  const sections = [];
  const sectionRanges = [];
  const used = /* @__PURE__ */ new Set();
  for (let i = 0; i < markers.length; i++) {
    const s = markers[i];
    if (s.type !== "start" || used.has(i))
      continue;
    let pairIdx = -1;
    for (let k = i + 1; k < markers.length; k++) {
      const e2 = markers[k];
      if (e2.type === "end" && !used.has(k) && e2.slideNum === s.slideNum && e2.hash === s.hash && e2.dup === s.dup) {
        pairIdx = k;
        break;
      }
    }
    if (pairIdx < 0)
      continue;
    used.add(i);
    used.add(pairIdx);
    const e = markers[pairIdx];
    sections.push({
      slideNum: s.slideNum,
      hash: s.hash,
      dup: s.dup,
      managed: body.slice(s.end, e.idx),
      after: ""
    });
    sectionRanges.push({ startIdx: s.idx, endIdxAfterMarker: e.end });
  }
  if (sections.length === 0) {
    return { frontmatter, preamble: body, sections: [] };
  }
  let preamble = body.slice(0, sectionRanges[0].startIdx);
  const slideH2 = preamble.match(/(^|\n)## 📚 슬라이드 \d+/);
  if (slideH2 && slideH2.index !== void 0) {
    const cutAt = slideH2.index + (slideH2[1] === "\n" ? 1 : 0);
    preamble = preamble.slice(0, cutAt);
  }
  for (let i = 0; i < sections.length; i++) {
    const range = sectionRanges[i];
    const fromIdx = range.endIdxAfterMarker;
    const nextRange = sectionRanges[i + 1];
    const candidateEnd = nextRange ? nextRange.startIdx : body.length;
    const slice = body.slice(fromIdx, candidateEnd);
    const nextH2 = slice.search(/(^|\n)## 📚 슬라이드 \d+/);
    if (nextH2 >= 0) {
      const cutAt = nextH2 + (slice[nextH2] === "\n" ? 1 : 0);
      sections[i].after = slice.slice(0, cutAt);
    } else {
      sections[i].after = slice;
    }
  }
  return { frontmatter, preamble, sections };
}
var LEFTOVER_LINE = new RegExp(`^(?:${SECTION_MARKER_PATTERN}|<!-- alt2obs:meta [^\\n]* -->)\\s*$`);

// src/core/slideMeta.ts
var META_RE = /\n*<!-- alt2obs:meta img:([0-9a-f]{128}|[0-9a-f]{64}|none) gist:("(?:[^"\\]|\\.)*") -->\s*$/;
function commentSafeJson(value) {
  return JSON.stringify(value).replace(/-/g, "\\u002d").replace(/>/g, "\\u003e");
}
function formatSlideMeta(imageSignal2, gist) {
  return `<!-- alt2obs:meta img:${imageSignal2 ?? "none"} gist:${commentSafeJson(gist)} -->`;
}
function parseSlideMeta(managed) {
  const m = managed.match(META_RE);
  if (!m)
    return null;
  try {
    return { imageSignal: m[1] === "none" ? null : m[1], gist: JSON.parse(m[2]) };
  } catch {
    return null;
  }
}
function stripSlideMeta(managed) {
  return managed.replace(META_RE, "");
}
var DIAGRAM_RE = /(^|\n+)(?:!\[\[[^\n]+?\.png\]\]|!\[[^\]\n]*\]\([^\n]+?\.png\))\s*$/;
function formatDiagramEmbed(vaultPath) {
  if (!/[#^[\]|]/.test(vaultPath))
    return `![[${vaultPath}]]`;
  const alt = (vaultPath.split("/").pop() ?? "").replace(/\.png$/, "").replace(/[#^[\]|]/g, " ").replace(/\s+/g, " ").trim();
  return `![${alt}](${vaultPath.split("/").map(encodeURIComponent).join("/")})`;
}
function stripDiagramEmbed(body) {
  return body.replace(DIAGRAM_RE, "");
}

// src/core/prep/TranscriptCompressor.ts
var KO_FILLERS = ["\uC74C", "\uC73C\uC74C", "\uC74C\uC74C", "\uC5B4", "\uC5B4\uC5B4", "\uC5D0", "\uC5D0\uC5D0", "\uADF8\uB7EC\uB2C8\uAE4C", "\uC800\uAE30", "\uADF8\uB2C8\uAE4C"];
var EN_FILLERS = ["um", "umm", "uh", "uhh", "uhm", "erm", "er", "hmm", "you know", "i mean"];
var PAUSE_FILLERS_RE = /(^|[\s,.!?])(?:뭐|아|ah)(?:,|…|\.{2,})(?=$|\s)/giu;
function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
var FILLER_RE = new RegExp(
  `(^|[\\s,.!?])(?:${[...KO_FILLERS, ...EN_FILLERS].sort((a, b) => b.length - a.length).map(escapeRegex).join("|")})(?:[,.\u2026]+|\\.{2,})?(?=$|[\\s,.!?])`,
  "giu"
);
function removeFillers(text) {
  let prev = "";
  let out = text;
  while (prev !== out) {
    prev = out;
    out = out.replace(FILLER_RE, "$1").replace(PAUSE_FILLERS_RE, "$1");
  }
  return out.replace(/[ \t]{2,}/g, " ").replace(/\s+([,.!?])/g, "$1").replace(/^[\s,]+/, "").trim();
}
function collapseRepeats(text) {
  const words = text.split(/\s+/).filter((w) => w.length > 0);
  const key = (w) => w.toLowerCase().replace(/[,.!?]+$/, "");
  const out = [];
  let i = 0;
  while (i < words.length) {
    let skipped = false;
    for (let n = 4; n >= 1; n--) {
      if (out.length < n || i + n > words.length)
        continue;
      let same = true;
      for (let k = 0; k < n; k++) {
        if (key(out[out.length - n + k]) !== key(words[i + k])) {
          same = false;
          break;
        }
      }
      if (same) {
        for (let k = 0; k < n; k++)
          out[out.length - n + k] = words[i + k];
        i += n;
        skipped = true;
        break;
      }
    }
    if (!skipped)
      out.push(words[i++]);
  }
  return out.join(" ");
}
function splitSentences(text) {
  return text.replace(/\s+/g, " ").split(/(?<=[.!?…])\s+|(?<=(?:다|요|죠|까|니다|습니다)[.!?]?)\s+(?=\S)/u).map((s) => s.trim()).filter((s) => s.length > 0);
}
function sentenceKey(s) {
  return s.normalize("NFC").toLowerCase().replace(/[\s,.!?…"'`]+/g, "");
}
function dedupeSentences(sentences) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const s of sentences) {
    const k = sentenceKey(s);
    if (k.length === 0 || seen.has(k))
      continue;
    const prev = out.length > 0 ? sentenceKey(out[out.length - 1]) : "";
    if (k.length >= 6 && prev.includes(k))
      continue;
    seen.add(k);
    out.push(s);
  }
  return out;
}
function contentTokens(text) {
  const tokens2 = /* @__PURE__ */ new Set();
  const lower = text.normalize("NFC").toLowerCase();
  for (const m of lower.matchAll(/[a-z0-9]{3,}|[가-힣]{2,}/g)) {
    const w = m[0];
    tokens2.add(w);
    if (/^[가-힣]/.test(w) && w.length > 2)
      tokens2.add(w.slice(0, 2));
  }
  return tokens2;
}
function capSentences(sentences, slideText, capChars) {
  if (capChars <= 0)
    return [];
  const total = sentences.reduce((n, s) => n + s.length + 1, 0);
  if (total <= capChars)
    return sentences;
  const slide = contentTokens(slideText);
  const scored = sentences.map((s, i) => {
    let score = 0;
    for (const t of contentTokens(s))
      if (slide.has(t))
        score++;
    return { i, s, score };
  });
  scored.sort((a, b) => b.score - a.score || a.i - b.i);
  const keep = /* @__PURE__ */ new Set();
  let used = 0;
  for (const c of scored) {
    if (used + c.s.length + 1 > capChars)
      continue;
    keep.add(c.i);
    used += c.s.length + 1;
  }
  return sentences.filter((_, i) => keep.has(i));
}
function compressTranscript(chunk, slideText, capChars) {
  if (!chunk || !chunk.trim())
    return { text: "", originalChars: 0 };
  const cleaned = collapseRepeats(removeFillers(chunk));
  const sentences = dedupeSentences(splitSentences(cleaned));
  return { text: capSentences(sentences, slideText, capChars).join(" "), originalChars: chunk.length };
}
function splitTranscriptEvenly(transcript, slideCount) {
  if (!transcript || slideCount === 0) {
    return new Array(slideCount).fill(null);
  }
  const chunkSize = Math.ceil(transcript.length / slideCount);
  const chunks = [];
  for (let i = 0; i < slideCount; i++) {
    const start = i * chunkSize;
    const end = Math.min(start + chunkSize, transcript.length);
    const chunk = transcript.slice(start, end).trim();
    chunks.push(chunk.length > 0 ? chunk : null);
  }
  return chunks;
}

// src/pipeline/batchPlan.ts
function parseExistingSlides(noteContent) {
  return splitMultiManagedNote(noteContent).sections.map((s) => {
    const meta = parseSlideMeta(s.managed);
    return {
      slideNum: s.slideNum,
      hash: s.hash,
      commentary: stripDiagramEmbed(stripSlideMeta(s.managed).trim()).trim(),
      imageSignal: meta?.imageSignal ?? null,
      gist: meta?.gist ?? "",
      meta: meta ? formatSlideMeta(meta.imageSignal, meta.gist) : ""
    };
  });
}
function slideChunks(slides, chunks) {
  const runChunks = slides.map((_, i) => chunks[i] ?? "");
  for (const s of [...slides].reverse()) {
    if (s.dupOf !== null && runChunks[s.page - 1]) {
      runChunks[s.dupOf - 1] = `${runChunks[s.page - 1]} ${runChunks[s.dupOf - 1]}`.trim();
      runChunks[s.page - 1] = "";
    }
  }
  return runChunks;
}
function planDeck(input) {
  const n = input.slides.length;
  const chunks = input.transcriptChunks ?? splitTranscriptEvenly(input.transcript, n);
  const runChunks = slideChunks(input.slides, chunks);
  const pool = /* @__PURE__ */ new Map();
  for (const e of input.existing ?? []) {
    if (!pool.has(e.hash))
      pool.set(e.hash, []);
    pool.get(e.hash).push(e);
  }
  let before = 0;
  let after = 0;
  const used = /* @__PURE__ */ new Set();
  const slides = input.slides.map((s, i) => {
    const text = input.layouts[i]?.text ?? "";
    const template = templateCommentary(s, input.deckTitle);
    if (template !== null)
      return { ...s, text, transcript: "", mode: "template", template };
    const candidates = pool.get(s.hash);
    const prev = candidates && candidates.length > 0 ? candidates.shift() : void 0;
    if (prev)
      used.add(prev);
    if (prev && prev.gist && s.imageSignal && sameImageSignal(prev.imageSignal, s.imageSignal)) {
      return { ...s, text, transcript: "", mode: "reuse", reused: { commentary: prev.commentary, gist: prev.gist } };
    }
    const compressed = compressTranscript(runChunks[i] || null, text, input.transcriptCapChars);
    before += compressed.originalChars;
    after += compressed.text.length;
    return { ...s, text, transcript: compressed.text, mode: "llm", previous: prev };
  });
  for (const s of slides) {
    if (s.mode !== "llm" || s.previous)
      continue;
    const byNum = (input.existing ?? []).find((e) => !used.has(e) && e.slideNum === s.page);
    if (byNum) {
      used.add(byNum);
      s.previous = byNum;
    }
  }
  return {
    slides,
    batches: makeBatches(slides, input.batchSize),
    scanned: input.scanned,
    transcriptChars: { before, after }
  };
}
function makeBatches(slides, batchSize) {
  const k = Math.max(1, Math.floor(batchSize));
  const kImg = Math.max(1, Math.floor(k / 2));
  const batches = [];
  let cur = { pages: [], hasImages: false };
  for (const s of slides) {
    if (s.mode !== "llm")
      continue;
    const hasImages = cur.hasImages || s.sendImage;
    const limit = hasImages ? kImg : k;
    if (cur.pages.length > 0 && cur.pages.length + 1 > limit) {
      batches.push(cur);
      cur = { pages: [], hasImages: false };
    }
    cur.pages.push(s.page);
    cur.hasImages = cur.hasImages || s.sendImage;
  }
  if (cur.pages.length > 0)
    batches.push(cur);
  return batches;
}

// src/utils/helpers.ts
function withoutControlChars(text) {
  let out = "";
  for (const ch of text)
    if (ch.charCodeAt(0) > 31)
      out += ch;
  return out;
}
function sanitizeFilename(name) {
  return withoutControlChars(name).replace(/[<>:"/\\|?*]/g, "").replace(/\.+$/, "").trim();
}

// src/vault/layout.ts
var LECTURES_DIR = "Lectures";
var ATTACHMENTS_DIR = "Attachments";
function join(...parts) {
  return parts.filter((p) => p.length > 0).join("/").replace(/\/{2,}/g, "/");
}
function attachmentStem(lectureStem) {
  return sanitizeFilename(lectureStem).replace(/[[\]#^|]/g, "").replace(/\s+/g, " ").trim() || "lecture";
}
function stemOf(path) {
  return (path.split("/").pop() ?? path).replace(/\.[^.]+$/, "");
}
function subjectFolderOfNote(notePath) {
  const parts = notePath.split("/");
  parts.pop();
  if (parts.length > 0 && parts[parts.length - 1] === LECTURES_DIR)
    parts.pop();
  return parts.join("/");
}
function attachmentPathForNote(notePath, page) {
  return join(subjectFolderOfNote(notePath), ATTACHMENTS_DIR, `${attachmentStem(stemOf(notePath))}-${page}.png`);
}

// scripts/src/cli-common.ts
import { readFile } from "node:fs/promises";
import { webcrypto } from "node:crypto";
function ensureWebCrypto() {
  if (!globalThis.crypto) {
    globalThis.crypto = webcrypto;
  }
}
async function openPdf(pdfPath) {
  ensureWebCrypto();
  console.log = (...args) => console.error(...args);
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const data = new Uint8Array(await readFile(pdfPath));
  return pdfjs.getDocument({ data, verbosity: 0 }).promise;
}
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/prep.ts
function option(args, name) {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : void 0;
}
function readPgmDir(dir, pageCount) {
  const grays = new Array(pageCount).fill(null);
  for (const f of readdirSync(dir)) {
    const m = f.match(/-(\d+)\.pgm$/);
    if (!m)
      continue;
    const page = parseInt(m[1], 10);
    if (page >= 1 && page <= pageCount)
      grays[page - 1] = parsePgm(new Uint8Array(readFileSync(join2(dir, f))));
  }
  return grays;
}
function renderWithPdftoppm(pdfPath, pageCount) {
  const dir = mkdtempSync(join2(tmpdir(), "alt2obs-prep-"));
  try {
    const r = spawnSync("pdftoppm", ["-gray", "-scale-to", String(ANALYSIS_LONG_EDGE), pdfPath, join2(dir, "p")], {
      stdio: ["ignore", "ignore", "pipe"]
    });
    if (r.status !== 0) {
      process.stderr.write("prep: pdftoppm not available, image ratio and image signal skipped\n");
      return new Array(pageCount).fill(null);
    }
    return readPgmDir(dir, pageCount);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}
async function main() {
  const args = process.argv.slice(2);
  const [pdfPath, sourceId] = args;
  if (!pdfPath || !sourceId || pdfPath.startsWith("--") || sourceId.startsWith("--")) {
    process.stderr.write("Usage: node scripts/phase2/prep.mjs <pdfPath> <sourceId> [--title T] [--transcript F | --bundle B] [--cap N] [--batch K] [--image-rule auto|text-only] [--renders DIR | --no-render] [--existing NOTE]\n");
    process.exit(2);
  }
  const imageRule = option(args, "--image-rule") === "text-only" ? "text-only" : "auto";
  const transcriptFile = option(args, "--transcript");
  const existingFile = option(args, "--existing");
  const rendersDir = option(args, "--renders");
  const notePath = option(args, "--note-path");
  const pdf = await openPdf(pdfPath);
  try {
    const layouts = await extractPageLayouts(pdf);
    const grays = args.includes("--no-render") ? new Array(layouts.length).fill(null) : rendersDir ? readPgmDir(rendersDir, layouts.length) : renderWithPdftoppm(pdfPath, layouts.length);
    const analysis = await analyzeSlides(layouts, grays, { sourceId, imageRule });
    const bundleFile = option(args, "--bundle");
    const segments = bundleFile ? JSON.parse(readFileSync(bundleFile, "utf8")).transcript : void 0;
    const alignment = alignLecture(layouts.map(layoutAlignmentText), segments, { scanned: analysis.scanned });
    const transcriptText = transcriptFile ? readFileSync(transcriptFile, "utf8") : segments ? segments.map((s) => s.text).join("\n") : null;
    const plan = planDeck({
      ...analysis,
      layouts,
      transcript: transcriptText,
      transcriptChunks: alignment?.chunks,
      transcriptCapChars: parseInt(option(args, "--cap") ?? "1200", 10),
      batchSize: parseInt(option(args, "--batch") ?? "8", 10),
      deckTitle: option(args, "--title") ?? "",
      existing: existingFile ? parseExistingSlides(readFileSync(existingFile, "utf8")) : void 0
    });
    const pages = plan.slides.map((s) => ({
      page: s.page,
      hash: s.hash,
      textChars: s.textChars,
      imageRatio: s.imageRatio,
      kind: s.kind,
      dupOf: s.dupOf,
      sendImage: s.sendImage,
      mode: s.mode,
      template: s.template ?? null,
      transcript: s.transcript,
      imageSignal: s.imageSignal,
      reusedGist: s.reused?.gist ?? null
    }));
    process.stdout.write(
      JSON.stringify({
        scanned: plan.scanned,
        transcriptChars: plan.transcriptChars,
        pages,
        batches: plan.batches.map((b) => b.pages),
        // Pages to save as images and embed (spec 4.8); empty without renders.
        keyDiagrams: selectKeyDiagrams(plan.slides, plan.scanned),
        keyDiagramFiles: notePath ? selectKeyDiagrams(plan.slides, plan.scanned).map((page) => {
          const path = attachmentPathForNote(notePath, page);
          return { page, path, embed: formatDiagramEmbed(path) };
        }) : null,
        alignment: alignment ? {
          value: alignment.value,
          spans: alignment.result.spans.map((s) => ({ slide: s.slide, startMs: s.startMs, endMs: s.endMs, confidence: s.confidence })),
          lowSpans: alignment.lowSpans.length
        } : null
      }) + "\n"
    );
  } finally {
    await pdf.destroy();
  }
}
main().catch((e) => fail(e, "prep"));
