// Generated by `npm run build:scripts` from scripts/src/slide-hashes.ts. Do not edit.

// scripts/src/slide-hashes.ts
import { readFile } from "node:fs/promises";
import { webcrypto } from "node:crypto";

// src/core/slideHash.ts
function normalizePageText(text) {
  return text.normalize("NFC").toLowerCase().replace(/\s+/g, "");
}
async function sha1Hex(input) {
  const digest = await crypto.subtle.digest("SHA-1", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function computeSlideHash(pageText, page, sourceId) {
  const normalized = normalizePageText(pageText);
  const key = normalized.length > 0 ? normalized : sourceId;
  return (await sha1Hex(`${key}:${page}`)).slice(0, 8);
}
async function extractPageTexts(pdf) {
  const texts = [];
  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    const page = await pdf.getPage(pageNum);
    const content = await page.getTextContent();
    texts.push(
      content.items.map((item) => item.str ?? "").join("")
    );
  }
  return texts;
}

// scripts/src/slide-hashes.ts
async function main() {
  const [pdfPath, sourceId] = process.argv.slice(2);
  if (!pdfPath || !sourceId) {
    process.stderr.write("Usage: node scripts/phase2/slide-hashes.mjs <pdfPath> <sourceId>\n");
    process.exit(2);
  }
  if (!globalThis.crypto) {
    globalThis.crypto = webcrypto;
  }
  console.log = (...args) => console.error(...args);
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const data = new Uint8Array(await readFile(pdfPath));
  const pdf = await pdfjs.getDocument({ data, verbosity: 0 }).promise;
  try {
    const texts = await extractPageTexts(pdf);
    const pages = [];
    for (let i = 0; i < texts.length; i++) {
      pages.push({
        page: i + 1,
        hash: await computeSlideHash(texts[i], i + 1, sourceId),
        textChars: normalizePageText(texts[i]).length
      });
    }
    process.stdout.write(JSON.stringify({ pages }) + "\n");
  } finally {
    await pdf.destroy();
  }
}
main().catch((e) => {
  process.stderr.write(`slide-hashes: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
});
