// Generated by `npm run build:scripts` from scripts/src. Do not edit.

// src/core/slideHash.ts
function normalizePageText(text) {
  return text.normalize("NFC").toLowerCase().replace(/\s+/g, "");
}
async function sha1Hex(input) {
  const digest = await crypto.subtle.digest("SHA-1", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function computeSlideHash(pageText, page, sourceId) {
  const normalized = pageText === null ? "" : normalizePageText(pageText);
  const key = normalized.length > 0 ? normalized : `${sourceId}:${page}`;
  return (await sha1Hex(key)).slice(0, 8);
}
async function extractPageTexts(pdf) {
  const texts = [];
  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    try {
      const page = await pdf.getPage(pageNum);
      const content = await page.getTextContent();
      texts.push(
        content.items.map((item) => item.str ?? "").join("")
      );
    } catch (e) {
      console.warn(`[Alt2Obsidian] text extraction failed for page ${pageNum}:`, e);
      texts.push(null);
    }
  }
  return texts;
}

// scripts/src/node-pdf.ts
import { readFile } from "node:fs/promises";
import { webcrypto } from "node:crypto";
async function openPdf(pdfPath) {
  if (!globalThis.crypto) {
    globalThis.crypto = webcrypto;
  }
  console.log = (...args) => console.error(...args);
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const data = new Uint8Array(await readFile(pdfPath));
  return pdfjs.getDocument({ data, verbosity: 0 }).promise;
}
function fail(e, name) {
  process.stderr.write(`${name}: ${e instanceof Error ? e.message : String(e)}
`);
  process.exit(1);
}

// scripts/src/slide-hashes.ts
async function main() {
  const [pdfPath, sourceId] = process.argv.slice(2);
  if (!pdfPath || !sourceId) {
    process.stderr.write("Usage: node scripts/phase2/slide-hashes.mjs <pdfPath> <sourceId>\n");
    process.exit(2);
  }
  const pdf = await openPdf(pdfPath);
  try {
    const texts = await extractPageTexts(pdf);
    const pages = [];
    for (let i = 0; i < texts.length; i++) {
      pages.push({
        page: i + 1,
        hash: await computeSlideHash(texts[i], i + 1, sourceId),
        textChars: normalizePageText(texts[i] ?? "").length
      });
    }
    process.stdout.write(JSON.stringify({ pages }) + "\n");
  } finally {
    await pdf.destroy();
  }
}
main().catch((e) => fail(e, "slide-hashes"));
