// Bundles the Node CLIs under scripts/src into scripts/phase2 (npm run build:scripts).
import esbuild from "esbuild";

esbuild
  .build({
    entryPoints: ["scripts/src/slide-hashes.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node18",
    external: ["pdfjs-dist"],
    outfile: "scripts/phase2/slide-hashes.mjs",
    banner: { js: "// Generated by `npm run build:scripts` from scripts/src/slide-hashes.ts. Do not edit." },
    logLevel: "info",
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
