// Bundles the Node CLIs under scripts/src into scripts/phase2 (npm run build:scripts).
// Optional argument: output directory (used by the freshness test).
import esbuild from "esbuild";

const outdir = process.argv[2] ?? "scripts/phase2";
const entries = ["slide-hashes", "lecture-material", "overview-block"];

esbuild
  .build({
    entryPoints: entries.map((name) => `scripts/src/${name}.ts`),
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node18",
    external: ["pdfjs-dist"],
    outdir,
    outExtension: { ".js": ".mjs" },
    banner: { js: "// Generated by `npm run build:scripts` from scripts/src. Do not edit." },
    logLevel: "info",
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
